import os
from itertools import product


symbols = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", 
"p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", " "]
combinations = product(symbols, repeat=9)


def create_folder(folder_name):
    if not os.path.exists(folder_name):
        os.makedirs(folder_name)

main_folder = "Library"
create_folder(main_folder)

folder_index = 1
page_index = 1
pages_per_book = 2000
aprox_chars_per_page = 5000
line_length = 80

current_folder = os.path.join(main_folder, f"Book_{folder_index}")
create_folder(current_folder)

current_content = ""
current_length = 0


def has_three_consecutive_chars(string):
    prev_char = None
    consecutive_count = 0
    for char in string:
        if char == prev_char:
            consecutive_count += 1
        else:
            prev_char = char
            consecutive_count = 1
        if consecutive_count >= 3:
            return True
    return False


def six_times_same_letter_or_too_few_distinct_ones(arg):

    # dict1 is used for finding enough distinct letters
    # dict2 is used to find 6 or more occurances of the same letter in a word
    dict1, dict2 = {}, {}

    for char in arg:
        if char != " ":
            try:
                dict1[char] += 1
                dict2[char] += 1

            except:
                dict1[char] = 1
                dict2[char] = 1
        else:
            # as words have to comply, not the whole combo itself
            dict2 = {}

    if len(arg) >= 10 and len(arg) <= 20 and len(dict1) <= 5 or len(arg) >= 20 and len(dict1) <= 8:
        return True

    for key in dict2:
        if dict1[key] > 5:
            return True

    return False


def letter_progressions(arg):
    # last spaces are added in order to tackle the index issues when last 3 chars are found
    # there don't have to be added any at the start of the array, as negative indexes fall into the same space chars already added
    chars = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", 
    "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", " ", " ", " "]
    
    for j in range(1, 8):
        for i in range(len(arg) - 3 * j):
            index_pos_in_array = chars.index(arg[i])
            if (
                (chars[index_pos_in_array + 1] == arg[i + 1 * j] and
                 chars[index_pos_in_array + 2] == arg[i + 2 * j] and
                 chars[index_pos_in_array + 3] == arg[i + 3 * j]) or 
                (chars[index_pos_in_array - 1] == arg[i + 1 * j] and
                 chars[index_pos_in_array - 2] == arg[i + 2 * j] and
                 chars[index_pos_in_array - 3] == arg[i + 3 * j])
                ):
                return True
    return False


for combination in combinations:
    combination_str = ''.join(combination)
    
    print(f"combination_str is {combination_str}")
    # Limits - start
    if "  " in combination_str:
        continue
    
    if has_three_consecutive_chars(combination_str):
        continue
    
    if six_times_same_letter_or_too_few_distinct_ones(combination_str):
        continue
    
    if combination_str.startswith(("bb", "dd", "gg")):
        continue
    
    if letter_progressions(combination_str):
        continue
    
    if any(substring in combination_str for substring in [" aa ", " bb ", " cc ", " dd ", 
        " ee ", " ff ", " gg ", " hh ", " ii ", " jj ", " kk ", " ll ", " mm ", " nn ", 
        " oo ", " pp ", " qq ", " rr ", " ss ", " tt ", " uu ", " vv ", " ww ", " xx ", 
        " yy ", " zz "]):
        continue

    for word in combination_str.split():
        vowels_check, consonants_check = 0, 0

        if len(word.strip()) >= 7 and word.strip() != "rhythms":
            if not any(substring in word.strip() for substring in ["a", "e", "i", "o", "u"]):
                vowels_check = 1
            if vowels_check == 1:
                break

        if len(word.strip()) >= 6 and word.strip() != "euouae":
            if not any(substring in word.strip() for substring in ["b", "c", "d", "f", "g", "h", "j", 
                "k", "l", "m", "n", "p", "q", "r", "s", "t", "v", "w", "x", "y", "z"]):
                consonants_check = 1
            if consonants_check == 1:
                break

    if any(substring in combination_str for substring in [
        "cj", "fq", "gx", "hx", "jf", "jq", "jx", 
        "jz", "qb", "qc", "qj", "qk", "qx", "qz", 
        "sx", "vf", "vj", "vq", "vx", "wx", "xj", "zx"
        ]):
        continue

    for word in combination_str.split():
        if any(substring == word.strip() for substring in [
            "aa", "bb", "cc", "dd", "ee", "ff", "gg", "hh", "ii", "jj", "kk", "ll", "mm", 
            "nn", "oo", "pp", "qq", "rr", "ss", "tt", "uu", "vv", "ww", "xx", "yy", "zz"
            ]):
            break
        
        if (len(word.strip()) == 2 or len(word.strip()) == 3) and word.strip() not in ['ver', 'hot', 'bam', 'oam', 'lee', 'psi', 'pap', 
            'wud', 'fon', 'dop', 'fl', 'udo', 'zan', 'lub', 'uhs', 'dlr', 'ark', 'eft', 'nea', 
            'nv', 'old', 'mtn', 'sox', 'ike', 'has', 'fol', 'dod', 'grs', 'cum', 'gan', 'mcf', 
            'xr', 'jog', 'mee', 'abs', 'fa', 'wha', 'noa', 'abp', 'zee', 'ggr', 'bay', 'ila', 
            'gtd', 'cu', 'due', 'awn', 'lxx', 'inn', 'tog', 'gox', 'meg', 'ssi', 'ned', 'cyl', 
            'nar', 'ary', 'el', 'jen', 'rhb', 'kil', 'hin', 'vu', 'woo', 'obi', 'gye', 'kua', 
            'khi', 'sec', 'bdl', 'xat', 'bob', 'tib', 'cpm', 'tlr', 'ed', 'pua', 'ghi', 'gel', 
            'yan', 'men', 'qr', 'end', 'goa', 'cal', 'wey', 'oot', 'ony', 'by', 'tri', 'lca', 
            'tau', 'ugh', 'fm', 'bah', 'dd', 'rho', 'lym', 'dca', 'ld', 'rat', 'dea', 'cg', 
            'ife', 'bas', 'kln', 'tfr', 'obl', 'yus', 'wag', 'gio', 'per', 'spl', 'taw', 'jab', 
            'dom', 'mym', 'liv', 'eam', 'eye', 'sen', 'aby', 'fil', 'pac', 'goo', 'eer', 'reb', 
            'ala', 'awl', 'nan', 'ipm', 'aba', 'psf', 'alb', 'kyu', 'apt', 'bad', 'kos', 'ami', 
            'qqv', 'ni', 'cst', 'auk', 'txt', 'sah', 'ora', 'shp', 'fug', 'gre', 'sta', 'mmf', 
            'boc', 'its', 'ist', 'quo', 'tae', 'liz', 'cl', 'kan', 'xii', 'ate', 'hex', 'eld', 
            'emp', 'grr', 'jut', 'pcf', 'cte', 'sc', 'soy', 'suq', 'uni', 'mfg', 'ge', 'adp', 
            'lit', 'vei', 'sky', 'pry', 'loy', 'adm', 'di', 'ivy', 'clr', 'aus', 'ha', 'ira', 
            'swy', 'alt', 'in', 'ppi', 'fw', 'sh', 'etc', 'op', 'fin', 'ohm', 'rei', 'qts', 
            'ret', 'ds', 'pad', 'io', 'pea', 'ort', 'lcm', 'rf', 'dew', 'elm', 'mam', 'obe', 
            'fp', 'abb', 'tot', 'bid', 'yod', 'wk', 'yew', 'rti', 'joe', 'vg', 'orl', 'jr', 
            'rib', 'gt', 'nye', 'doc', 'whs', 'lai', 'ohs', 'lr', 'ot', 'oat', 'bod', 'who', 
            'wir', 'sma', 'dcb', 'puy', 'ere', 'jim', 'gi', 'bus', 'at', 'lie', 'suf', 'rog', 
            'ree', 'lei', 'dl', 'tug', 'rle', 'sim', 'nco', 'dis', 'pye', 'cap', 'pks', 'hap', 
            'aru', 'ebb', 'tsp', 'byp', 'sit', 'taa', 'hug', 'sld', 'bum', 'mig', 'job', 'elk', 
            'prn', 'pug', 'yds', 'rhd', 'la', 'haj', 'isz', 'vas', 'amu', 'ch', 'gin', 'wf', 
            'val', 'sps', 'yez', 'hob', 'usu', 'saw', 'ob', 'six', 'usw', 'ahs', 'nt', 'din', 
            'why', 'fot', 'hts', 'inc', 'em', 'ova', 'wab', 'lyc', 'mug', 'ply', 'plu', 'wos', 
            'gag', 'llb', 'van', 'yoe', 'joy', 'ppt', 'pci', 'sly', 'kra', 'hal', 'ran', 'ijo', 
            'dia', 'uri', 'ow', 'abd', 'eng', 'as', 'yn', 'mt', 'fou', 'can', 'ito', 'seq', 'mc', 
            'taj', 'cav', 'oy', 'fac', 'eff', 'dpt', 'gra', 'bsf', 'll', 'jus', 'og', 'edo', 
            'hcb', 'aeq', 'pul', 'ptp', 'laz', 'jef', 'efs', 'kam', 'mom', 'suu', 'is', 'un', 
            'pcm', 'sk', 'pl', 'kou', 'tb', 'br', 'sb', 'mgd', 'owl', 'doz', 'yad', 'box', 'qto', 
            'pis', 'eos', 'qed', 'meo', 'xi', 'baa', 'wee', 'bud', 'mcg', 'cow', 'obb', 'aum', 
            'oki', 'hom', 'kaw', 'pkg', 'ms', 'dc', 'say', 'emm', 'tic', 'wer', 'sei', 'lux', 
            'ys', 'mss', 'typ', 'paw', 'jcl', 'dev', 'rem', 'yam', 'cpo', 'ppr', 'lut', 'one', 
            'ket', 'pf', 'mw', 'won', 'alg', 'oke', 'ung', 'ink', 'apx', 'jag', 'xd', 'sny', 
            'yun', 'imu', 'lwm', 'zar', 'ups', 'kw', 'lf', 'chn', 'vai', 'moi', 'fum', 'rod', 
            'max', 'hes', 'oii', 'nus', 'vog', 'day', 'kgf', 'got', 'eo', 'nd', 'aho', 'gas', 
            'yet', 'lew', 'azo', 'pat', 'bey', 'aku', 'ell', 'msg', 'gyp', 'lhd', 'km', 'pav', 
            'def', 'ont', 'att', 'whf', 'jat', 'edp', 'apr', 'fo', 'krs', 'ash', 'rip', 'cyc', 
            'erk', 'zod', 'rap', 'ibo', 'sir', 'lod', 'heo', 'aid', 'tsk', 'faq', 'aim', 'tax', 
            'zoo', 'dao', 'ref', 'tie', 'toi', 'cd', 'tpk', 'ips', 'top', 'rfb', 'bnf', 'hoo', 
            'ken', 'toe', 'loq', 'urb', 'ext', 'sup', 'ptg', 'hup', 'gov', 'ax', 'aer', 'ure', 
            'nbg', 'rab', 'med', 'nix', 'cpl', 'stu', 'kat', 'sil', 'kol', 'ana', 'kye', 'spp', 
            'me', 'nob', 'vv', 'mao', 'ihp', 'vag', 'lst', 'brr', 'tef', 'lop', 'dsp', 'woy', 
            'chi', 'pam', 'nj', 'dob', 'tel', 'osi', 'jan', 'tag', 'pk', 'oik', 'als', 'mas', 
            'nog', 'qat', 'mes', 'pkt', 'hu', 'gcd', 'dx', 'te', 'fc', 'nef', 'hol', 'ego', 
            'yak', 'cun', 'syr', 'bx', 'enl', 'gnu', 'atm', 'my', 'bub', 'tee', 'uva', 'aux', 
            'bur', 'wap', 'duo', 'soh', 'pc', 'sab', 'fig', 'ems', 'stk', 'wjc', 'roo', 'wiz', 
            'nek', 'eth', 'roc', 'cro', 'syd', 'oak', 'oto', 'hl', 'sax', 'ab', 'sal', 'cam', 
            'keg', 'agr', 'az', 'ump', 'jin', 'sau', 'iso', 'wry', 'bat', 'jow', 'ren', 'yok', 
            'wu', 'kee', 'asp', 'fed', 'aln', 'meq', 'lyn', 'wa', 'jud', 'loc', 'rcd', 'veg', 
            'dol', 'pwr', 'vr', 'hau', 'tc', 'law', 'rt', 'shu', 'pon', 'rc', 'ho', 'tut', 'ush', 
            'xx', 'sad', 'cox', 'dui', 'oni', 'ory', 'ors', 'tch', 'oes', 'sod', 'big', 'dag', 
            'fps', 'wok', 'wef', 'use', 'mru', 'ola', 'geo', 'pop', 'dwt', 'tm', 'cis', 'fut', 
            'nut', 'aix', 'vet', 'ado', 'pa', 'off', 'ult', 'yox', 'gl', 'tew', 'trs', 'tgt', 
            'bhd', 'ml', 'pwt', 'heh', 'uc', 'awk', 'ppd', 'urn', 'cpt', 'hox', 'tbs', 'ao', 
            'oos', 'ino', 'ack', 'gro', 'ilk', 'yon', 'dug', 'kop', 'haf', 'ety', 'qn', 'fy', 
            'bro', 'lim', 'pob', 'hui', 'rev', 'vin', 'hr', 'erd', 'rfz', 'ecb', 'aht', 'enc', 
            'nl', 'the', 'fro', 'ach', 'zed', 'bot', 'tsi', 'bvt', 'kha', 'est', 'bow', 'unb', 
            'pro', 'act', 'hye', 'tux', 'cif', 'sic', 'cit', 'jms', 'sow', 'hd', 'rah', 'pod', 
            'leo', 'mal', 'mag', 'cdr', 'sig', 'en', 'ane', 'wis', 'bg', 'ef', 'kaj', 'tr', 
            'gee', 'nol', 'dys', 'hei', 'mp', 'kay', 'dye', 'fee', 'usa', 'sla', 'ars', 'pep', 
            'bi', 'mos', 'san', 'lui', 'loo', 'ita', 'ean', 'arb', 'wpm', 'iou', 'cig', 'lac', 
            'fen', 'pyr', 'iff', 'va', 'nm', 'uke', 'oof', 'gis', 'hak', 'clo', 'ods', 'thy', 
            'jon', 'hq', 'ga', 'jed', 'lur', 'ked', 'sds', 'dkl', 'mev', 'boo', 'cor', 'kb', 
            'phi', 'qt', 'eau', 'uca', 'kor', 'dur', 'lbw', 'li', 'ts', 'qtd', 'alk', 'few', 
            'ers', 'ie', 'ct', 'tit', 'nul', 'git', 'iof', 'ko', 'ace', 'reg', 'gtt', 'ecu', 
            'acy', 'gip', 'ep', 'frt', 'fod', 'bt', 'sgd', 'rew', 'sel', 'bf', 'pun', 'nos', 
            'oe', 'std', 'tay', 'cq', 'hm', 'mbd', 'eom', 'ht', 'div', 'unl', 'ea', 'sar', 'jug', 
            'key', 'fab', 'uns', 'ce', 'com', 'utu', 'lug', 'now', 'tpm', 'elt', 'jai', 'yee', 
            'nil', 'kob', 'gos', 'yom', 'ad', 'lip', 'nap', 'isl', 'oaf', 'tph', 'dat', 'st', 
            'doe', 'ak', 'ng', 'ear', 'awd', 'fcp', 'hae', 'sos', 'pho', 'dak', 'fez', 'fz', 
            'chg', 'adz', 'sak', 'zip', 'sed', 'vie', 'cul', 'dun', 'baw', 'hb', 'sf', 'cai', 
            'vc', 'fry', 'phr', 'agy', 'fey', 'dkm', 'lin', 'fu', 'cat', 'wei', 'dow', 'nr', 
            'lay', 'yrs', 'ban', 'se', 'ai', 'bit', 'lot', 'iv', 'pfg', 'rut', 'aff', 'cpi', 
            'adv', 'vs', 'gup', 'no', 'poy', 'ise', 'tu', 'lwp', 'flo', 'ing', 'bp', 'app', 
            'sav', 'abe', 'ons', 'vox', 'jct', 'gem', 'fow', 'cpd', 'mgr', 'gps', 'dt', 'wah', 
            'int', 'ron', 'spa', 'kai', 'wod', 'ap', 'nay', 'hah', 'tra', 'msl', 'boe', 'tv', 
            'ges', 'gp', 'yot', 'ios', 'stm', 'ian', 'za', 'tin', 'wur', 'owt', 'pud', 'iyo', 
            'oh', 'min', 'dim', 'map', 'sr', 'dix', 'kea', 'umm', 'owk', 'ake', 'yi', 'ter', 
            'pur', 'lm', 'bop', 'dum', 'pg', 'man', 'dey', 'ive', 'rex', 'wg', 'ppl', 'bhp', 
            'dtd', 'fas', 'lof', 'vee', 'ltr', 'nun', 'hs', 'viz', 'nee', 'zac', 'wet', 'qaf', 
            'hub', 'mi', 'ins', 'aah', 'hcf', 'fth', 'lnr', 'sew', 'js', 'vo', 'uh', 'nis', 
            'rux', 'bef', 'adc', 'soe', 'btl', 'air', 'ppm', 'gun', 'guz', 'kin', 'hep', 'du', 
            'jew', 'scr', 'ufo', 'on', 'eon', 'cry', 'rit', 'fer', 'sog', 'ix', 'let', 'mar', 
            'goi', 'wid', 'emf', 'pps', 'tos', 'tob', 'gue', 'tox', 'tao', 'tom', 'not', 'sou', 
            'myc', 'dit', 'pvt', 'crl', 'rag', 'lep', 'ta', 'sem', 'huh', 'yo', 'asb', 'iqs', 
            'os', 'erf', 'ens', 'khu', 'hid', 'lwl', 'pal', 'ted', 'es', 'aly', 'csc', 'ptt', 
            'ger', 'ton', 'yor', 'jah', 'buz', 'sao', 'tap', 'kex', 'bde', 'vel', 'add', 'bac', 
            'den', 'car', 'ord', 'wig', 'cly', 'ro', 'gld', 'ex', 'alp', 'frs', 'see', 'tyg', 
            'rud', 'gab', 'ade', 'shy', 'het', 'lax', 'cgm', 'tab', 'xw', 'don', 'dyn', 'cha', 
            'rig', 'yr', 'reh', 'xiv', 'hen', 'xix', 'ir', 'lt', 'eq', 'nam', 'kue', 'moe', 
            'qrs', 'log', 'xed', 'qs', 'civ', 'mtx', 'gor', 'ago', 'kep', 'dud', 'nav', 'lir', 
            'fud', 'xs', 'raw', 'tor', 'lum', 'wae', 'sch', 'esu', 'luc', 'id', 'wac', 'zax', 
            'mim', 'pt', 'poh', 'bai', 'co', 'ako', 'ada', 'abo', 'kgr', 'wow', 'bel', 'dr', 
            'hv', 'ava', 'bk', 'dem', 'nub', 'tuy', 'wad', 'qe', 'naf', 'blo', 'ham', 'jg', 
            'pas', 'go', 'qh', 'nou', 'rs', 'sol', 'ka', 'opa', 'ssp', 'era', 'aes', 'arn', 
            'lat', 'feh', 'var', 'poz', 'ey', 'uru', 'ui', 'dbl', 'how', 'syn', 'mfr', 'ubi', 
            'ski', 'obv', 'win', 'iud', 'bch', 'wem', 'rn', 'yap', 'sw', 'mou', 'our', 'so', 
            'ida', 'nim', 'oie', 'fv', 'aob', 'ctf', 'fll', 'er', 'bab', 'sie', 'all', 'xcl', 
            'neb', 'ji', 'bu', 'dan', 'sa', 'bps', 'mo', 'lcd', 'han', 'pos', 'oda', 'and', 
            'qui', 'gog', 'pie', 'sv', 'mwa', 'ask', 'amp', 'isn', 'peh', 'ky', 'cts', 'od', 
            'lif', 'uds', 'abv', 'ler', 'fgn', 'cho', 'ccm', 'lad', 'hp', 'av', 'ant', 'saa', 
            'jet', 'nod', 'rpt', 'avn', 'clk', 'nag', 'jeg', 'hon', 'gds', 'hia', 'tss', 'vax', 
            'tyr', 'guy', 'tpd', 'poi', 'gat', 'fix', 'pir', 'rya', 'tan', 'mew', 'sop', 'teg', 
            'dz', 'els', 'prp', 'rua', 'ipr', 'rte', 'tmh', 'hoe', 'noy', 'tk', 'pts', 'yis', 
            'len', 'kyl', 'pol', 'crc', 'jur', 'of', 'rie', 'cli', 'nig', 'eel', 'cto', 'om', 
            'mph', 'ais', 'yeo', 'any', 'tur', 'voc', 'tov', 'dip', 'ave', 'pq', 'kie', 'ly', 
            'bkg', 'hld', 'bld', 'fb', 'mkt', 'hod', 'glt', 'ess', 'ock', 'orf', 'mb', 'eg', 
            'uta', 'kru', 'pen', 'gae', 'tyt', 'cre', 'moc', 'tav', 'rio', 'kv', 'uts', 'alo', 
            'sex', 'ata', 'req', 'fit', 'ddt', 'boy', 'via', 'rik', 'bar', 'ufs', 'gpm', 'pee', 
            'spy', 'ql', 'qua', 'ela', 'ux', 'lye', 'unc', 'mxd', 'ctg', 'lud', 'pip', 'gns', 
            'cia', 'rum', 'vb', 'tck', 'eke', 'ns', 'ape', 'mks', 'mad', 'fox', 'yat', 'cid', 
            'dal', 'que', 'ffa', 'cup', 'uti', 'set', 'aw', 'roy', 'bcd', 'mid', 'svc', 'hie', 
            'mat', 'erg', 'yep', 'zat', 'env', 'fi', 'och', 'abc', 'wim', 'ctn', 'gol', 'rfs', 
            'lg', 'ale', 'mab', 'cwt', 'ur', 'irk', 'im', 'sct', 'orb', 'arg', 'iq', 'dn', 'ag', 
            'dsr', 'ama', 'jo', 'pox', 'iao', 'hy', 'sey', 'pe', 'pah', 'yuh', 'pet', 'moy', 
            'btu', 'hee', 'jaw', 'ion', 'pbx', 'amb', 'il', 'phu', 'nb', 'sis', 'his', 'md', 
            'wan', 'hip', 'opt', 'dap', 'nox', 'pte', 'moa', 'neg', 'cir', 'net', 'hag', 'ule', 
            'rnd', 'kt', 'kab', 'oxy', 'coy', 'bra', 'ram', 'ich', 'sci', 'ra', 'pus', 'ras', 
            'dzo', 'lao', 'org', 'aft', 'wi', 'hao', 'arr', 'zea', 'rct', 'qty', 'bm', 'yoi', 
            'vol', 'tub', 'pau', 'ye', 'ads', 'cr', 'mgt', 'mr', 'new', 'vav', 'sha', 'lan', 
            'ut', 'lb', 'bun', 'qy', 'cep', 'rot', 'les', 'ain', 'ju', 'amt', 'gyn', 'wc', 
            'gap', 'nu', 'yeh', 'wyn', 'twi', 'beg', 'yup', 'doh', 'wed', 'sob', 'hav', 'arc', 
            'ros', 'obs', 'na', 'ese', 'ck', 'tua', 'mya', 'age', 'ug', 'may', 'hed', 'vt', 
            'cag', 'war', 'unp', 'gob', 'moo', 'suk', 'cps', 'woe', 'ids', 'sl', 'cdg', 'gtc', 
            'hud', 'mts', 'lhb', 'kg', 'apl', 'nat', 'ulu', 'bb', 'umu', 'cud', 'arm', 'xxi', 
            'art', 'bul', 'qu', 'icy', 'lor', 'iw', 'wro', 'eyr', 'tye', 'pmt', 'fay', 'gte', 
            'yid', 'an', 'tx', 'mib', 'ohv', 'aug', 'wr', 'mn', 'bon', 'nad', 'tex', 'mna', 
            'ire', 'ud', 'exp', 'db', 'tho', 'sok', 'con', 'juv', 'yd', 'sea', 'hoy', 'nor', 
            'rid', 'duc', 'le', 'ac', 'bed', 'run', 'ker', 'fat', 'bxs', 'ls', 'fib', 'eof', 
            'doo', 'gn', 'ose', 'mk', 'elb', 'pyx', 'elf', 'gud', 'trp', 'cay', 'mus', 'oct', 
            'rh', 'del', 'mtd', 'abl', 'tec', 'dks', 'yum', 'mpg', 'ode', 'nid', 'dam', 'slt', 
            'guv', 'roi', 'bn', 'eu', 'gou', 'ugt', 'out', 'hum', 'ihs', 'iwa', 'exr', 'et', 
            'mhz', 'ne', 'get', 'vau', 'hoc', 'rel', 'tad', 'vod', 'cod', 'tip', 'mtg', 'plf', 
            'ofo', 'jnd', 'qtr', 'ozs', 'lob', 'num', 'acc', 'fpm', 'aal', 'piu', 'mah', 'urs', 
            'cad', 'ppa', 'yah', 'ish', 'sov', 'sri', 'hgt', 'mis', 'lak', 'sn', 'oft', 'yen', 
            'huk', 'gut', 'caw', 'ati', 'awm', 'aud', 'oad', 'cos', 'pli', 'mpb', 'ged', 'sym', 
            'pr', 'pu', 'rm', 'dex', 'zad', 'jay', 'cgs', 'gul', 'yea', 'voe', 'tue', 'wax', 
            'pre', 'coo', 'cog', 'ume', 'awa', 'noh', 'obj', 'wb', 'you', 'bea', 'do', 'ifs', 
            'von', 'cyp', 'raj', 'aul', 'pfx', 'rpm', 'dib', 'mer', 'cml', 'hab', 'hoi', 'mog', 
            'fe', 'kal', 'oc', 'daw', 'gu', 'wo', 'qid', 'hf', 'dg', 'kc', 'bbl', 'sun', 'ayu', 
            'bz', 'prf', 'are', 'kef', 'yar', 'zep', 'flu', 'mud', 'tol', 'lbf', 'dei', 'imi', 
            'bom', 'sac', 'uro', 'low', 'zag', 'fly', 'sia', 'bap', 'riv', 'was', 'olm', 'lea', 
            'poe', 'mun', 'chs', 'vil', 'ind', 'gry', 'hvy', 'fei', 'owd', 'jig', 'to', 'cee', 
            'yas', 'shh', 'dor', 'bor', 'ima', 'cfh', 'cp', 'vip', 'dad', 'gad', 'tum', 'ope', 
            'iba', 'qp', 'apa', 'bys', 'bae', 'lib', 'cpu', 'dk', 'oar', 'epa', 'oui', 'bks', 
            'ft', 'ped', 'wob', 'kas', 'haw', 'yer', 'gey', 'fs', 'mux', 'jos', 'way', 'auf', 
            'udi', 'cy', 'mv', 'dhu', 'kui', 'roe', 'irs', 'sib', 'sm', 'amy', 'zen', 'yuk', 
            'hay', 'ma', 'al', 'fad', 'lap', 'ono', 'tod', 'sus', 'ull', 'tig', 'hg', 'aik', 
            'gur', 'che', 'por', 'tal', 'dig', 'chm', 'mac', 'nth', 'yip', 'kif', 'row', 'spt', 
            'pia', 'rom', 'ans', 'iph', 'ber', 'poa', 'jak', 'ln', 'gam', 'had', 'mea', 'ppb', 
            'wye', 'mor', 'mol', 'pya', 'sty', 'ula', 'uji', 'vaw', 'lv', 'lav', 'dab', 'abu', 
            'ic', 'rye', 'kae', 'lu', 'ani', 'jun', 'mf', 'tez', 'cs', 'csk', 'sae', 'bug', 'vp', 
            'mum', 'tty', 'zo', 'upo', 'xxx', 'tst', 'tp', 'rax', 'lig', 'jar', 'pay', 'fid', 
            'pmk', 'pot', 'deb', 'fop', 'cur', 'zn', 'pup', 'him', 'aha', 'inv', 'neo', 'hrs', 
            'sye', 'ib', 'dae', 'cdf', 'gau', 'fur', 'tun', 'sat', 'ihi', 'ahi', 'bv', 'sur', 
            'gaw', 'yex', 'tg', 'ckw', 'mob', 'sp', 'mm', 'ead', 'koa', 'naa', 'da', 'tha', 
            'wmk', 'ria', 'jem', 'eco', 'oz', 'inf', 'gv', 'pow', 'shr', 'ops', 'fiz', 'wot', 
            'wun', 'tar', 'own', 'pi', 'sml', 'hw', 'be', 'ore', 'ah', 'lex', 'wit', 'ipl', 
            'ahu', 'ley', 'gym', 'arx', 'mem', 'or', 'fr', 'cfd', 'td', 'hut', 'cv', 'par', 
            'try', 'dec', 'cop', 'wy', 'gm', 'tim', 'foh', 'bl', 'oba', 'saj', 'fip', 'ide', 
            'tpi', 'dar', 'lys', 'rix', 'yoy', 'jnt', 'ss', 'bos', 'eh', 'myg', 'lam', 'scf', 
            'um', 'doa', 'hwa', 'die', 'dil', 'dj', 'rim', 'rug', 'mh', 'kyd', 'ia', 'fbi', 
            'fra', 'wut', 'ps', 'jad', 'vss', 'vug', 'mir', 'hwt', 'th', 'mod', 'hem', 'vi', 
            'evg', 'sep', 'tui', 'tat', 'dos', 'ar', 'fir', 'mow', 'csw', 'he', 'bye', 'bsh', 
            'auh', 'pic', 'gie', 'mel', 'bee', 'wat', 'osc', 'si', 'mit', 'toy', 'kn', 'oms', 
            'dp', 'bkt', 'hhd', 'yin', 'xis', 'aga', 'hat', 'am', 'pew', 'bpt', 'wd', 'hny', 
            'bo', 'ws', 'yes', 'aas', 'kaf', 'cf', 'cwm', 'sam', 'pp', 'sho', 'suz', 'ara', 
            'pty', 're', 'mop', 'geb', 'ae', 'arf', 'ol', 'oka', 'po', 'sot', 'gif', 'swa', 
            'af', 'ox', 'kpc', 'egg', 'rwd', 'mot', 'dkg', 'trt', 'gez', 'lid', 'sqd', 'ny', 
            'agt', 'rec', 'bal', 'hyd', 'dir', 'emu', 'opp', 'ksi', 'ok', 'leu', 'das', 'mia', 
            'dog', 'tup', 'bs', 'zig', 'rin', 'owe', 'odz', 'ew', 'bag', 'ann', 'pub', 'tid', 
            'wog', 'cut', 'wl', 'zap', 'eyn', 'hop', 'eir', 'pdq', 'yow', 'tis', 'wt', 'nip', 
            'wup', 'ill', 'oer', 'ady', 'yaw', 'vii', 'luo', 'led', 'zho', 'loe', 'ben', 'eme', 
            'rwy', 'bds', 'rly', 'olp', 'bbs', 'gib', 'deg', 'prs', 'cot', 'wm', 'sg', 'zak', 
            'fcs', 'lh', 'mho', 'lag', 'flb', 'fg', 'crs', 'vat', 'jer', 'but', 'she', 'fld', 
            'ssu', 'lue', 'gaj', 'tdr', 'son', 'tji', 'ase', 'rha', 'alc', 'ile', 'vum', 'fn', 
            'orc', 'lox', 'sui', 'oil', 'tem', 'kit', 'vex', 'axe', 'loa', 'wea', 'pax', 'alf', 
            'aa', 'pht', 'ya', 'zit', 'kon', 'bpi', 'feu', 'cwo', 'rus', 'anc', 'stg', 'peg', 
            'ign', 'it', 'yob', 'goy', 'cmd', 'buy', 'tiu', 'sum', 'yao', 'kl', 'coz', 'ja', 
            'tkt', 'pdn', 'waf', 'mg', 'awe', 'hel', 'twp', 'pit', 'bet', 'ait', 'pes', 'gim', 
            'hit', 'urf', 'det', 'ism', 'cfm', 'jib', 'for', 'nei', 'tnt', 'esc', 'nep', 'ser', 
            'glb', 'ubc', 'asa', 'wh', 'mu', 'met', 'pct', 'pst', 'sht', 'nae', 'gil', 'gal', 
            'gig', 'wop', 'rld', 'rhe', 'fwd', 'nit', 'sid', 'rd', 'gr', 'col', 'una', 'noo', 
            'jee', 'hwy', 'naw', 'jot', 'cie', 'ole', 'koi', 'err', 'fem', 'abn', 'tps', 'mil', 
            'lsc', 'tow', 'csi', 'iva', 'vic', 'res', 'ura', 'pdl', 'rue', 'too', 'eli', 'dha', 
            'itd', 'ewe', 'tea', 'fub', 'vac', 'yug', 'syl', 'aro', 'hew', 'soc', 'did', 'ass', 
            'twa', 'avo', 'sfm', 'ays', 'bio', 'urd', 'pph', 'sin', 'fob', 'dau', 'ast', 'yay', 
            'gph', 'gs', 'bim', 'bec', 'yed', 'kid', 'aor', 'til', 'rok', 'mae', 'ame', 'rad', 
            'bib', 'las', 'epi', 'ail', 'lou', 'oud', 'hir', 'lo', 'aam', 'xvi', 'cub', 'tng', 
            'jt', 'lah', 'cue', 'ay', 'csp', 'kip', 'pix', 'woa', 'der', 'qv', 'lx', 'sq', 
            'pfd', 'iii', 'aet', 'uit', 'waw', 'ik', 'mix', 'aka', 'ki', 'ph', 'zs', 'kim', 
            'aph', 'sfz', 'ccw', 'ldg', 'red', 'dm', 'eva', 'rtw', 'rps', 'vd', 'boh', 'yt', 
            'alw', 'hic', 'rox', 'lis', 'cab', 'kr', 'kph', 'oho', 'zer', 'vow', 'vim', 'vl', 
            'blk', 'nom', 'een', 'rub', 'sd', 'whr', 'cc', 'gon', 'pta', 'foo', 'pil', 'lc', 
            'toa', 'psw', 'coe', 'ii', 'ona', 'bog', 'fec', 'mau', 'gum', 'tgn', 'lev', 'ust', 
            'wus', 'fam', 'liq', 'pm', 'eds', 'tam', 'tlo', 'rep', 'gpd', 'mlx', 'aq', 'tai', 
            'cb', 'her', 'gay', 'asg', 'grf', 'fae', 'jap', 'pfc', 'mfd', 'god', 'sai', 'zel', 
            'tou', 'aaa', 'fun', 'dft', 'dry', 'pim', 'pd', 'esq', 'esp', 'caf', 'abr', 'xu', 
            'abt', 'hue', 'zoa', 'tn', 'leg', 'dot', 'bis', 'ern', 'biz', 'lab', 'if', 'cru', 
            'vis', 'avg', 'cuj', 'rms', 'lar', 'us', 'hi', 'pik', 'ooh', 'keb', 'eat', 'ym', 
            'ti', 'bcf', 'su', 'efl', 'dub', 'cfs', 'xxv', 'maw', 'dif', 'rg', 'shi', 'wen', 
            'pig', 'nak', 'ric', 'ca', 'aye', 'dep', 'dux', 'brl', 'mhg', 'ctr', 'far', 'bes', 
            'sag', 'web', 'nab', 'ec', 'des', 'jeu', 'fmt', 'ba', 'eve', 'xc', 'nov', 'ff', 
            'cen', 'hsi', 'lbs', 'gd', 'sub', 'pan', 'gus', 'gen', 'rea', 'fet', 'nib', 'fie', 
            'ouf', 'adj', 'hcl', 'eyl', 'gar', 'cob', 'meu', 'str', 'bd', 'bin', 'lwo', 'dee', 
            'xyz', 'odd', 'dah', 'gaz', 'we', 'lp', 'pin', 'hey', 'foe', 'sip', 'rob', 'zek', 
            'unn', 'sue', 'ray', 'np', 'grx', 'otc', 'ibm', 'two', 'tas', 'fog', 'tln', 'foy', 
            'hun', 'ten', 'bol', 'bls', 'gid', 'put', 'ice', 'fcy', 'pom', 'sud', 'mut', 'qm', 
            'hyp', 'sqq', 'cm', 'ido', 'boa', 'mrs', 'fax', 'jam', 'fan', 'ee', 'eta', 'hor', 
            'de', 'non', 'edh', 'up', 'oca', 'hog', 'dy', 'mon', 'wes', 'trf', 'fag', 'ute', 
            'afd', 'afb', 'dup', 'lek', 'lpm', 'imp', 'sap', 'esd', 'seg', 'ald', 'cfi'
            ]:
            break
    
    if any(substring in combination_str for substring in [
        'aaj', 'aao', 'aaq', 'aav', 'aax', 'aay', 'abq', 'abx', 'acg', 'acj', 'acv', 'acz', 
        'adx', 'aej', 'afj', 'afp', 'afq', 'afv', 'afx', 'agj', 'agq', 'agx', 'agz', 'ahq', 
        'ahx', 'ajc', 'ajd', 'ajf', 'ajg', 'ajk', 'ajq', 'ajt', 'ajv', 'ajw', 'ajx', 'ajy', 
        'ajz', 'akj', 'akq', 'akx', 'amq', 'amx', 'aoa', 'aoj', 'aoq', 'apg', 'apq', 'apv', 
        'apz', 'aqb', 'aqc', 'aqd', 'aqe', 'aqf', 'aqg', 'aqh', 'aqj', 'aqk', 'aqm', 'aqn', 
        'aqp', 'aqr', 'aqt', 'aqv', 'aqw', 'aqx', 'aqy', 'aqz', 'asx', 'atq', 'atx', 'auo', 
        'avb', 'avf', 'avh', 'avj', 'avk', 'avm', 'avp', 'avq', 'avt', 'avw', 'avx', 'avz', 
        'awj', 'awv', 'awx', 'axj', 'axq', 'axr', 'axv', 'axx', 'axz', 'ayj', 'ayq', 'ayx', 
        'azb', 'azc', 'azj', 'azk', 'azq', 'azv', 'azw', 'azx', 'bbb', 'bbc', 'bbd', 'bbf', 
        'bbg', 'bbh', 'bbj', 'bbk', 'bbn', 'bbp', 'bbq', 'bbt', 'bbv', 'bbw', 'bbx', 'bbz', 
        'bcb', 'bcc', 'bcg', 'bcj', 'bck', 'bcm', 'bcn', 'bcp', 'bcq', 'bcs', 'bct', 'bcv', 
        'bcw', 'bcx', 'bcz', 'bdb', 'bdc', 'bdd', 'bdg', 'bdh', 'bdj', 'bdk', 'bdm', 'bdn', 
        'bdp', 'bdq', 'bdv', 'bdx', 'bdy', 'bdz', 'bfb', 'bfc', 'bfd', 'bff', 'bfg', 'bfh', 
        'bfj', 'bfk', 'bfm', 'bfn', 'bfp', 'bfq', 'bfs', 'bft', 'bfv', 'bfw', 'bfx', 'bfy', 
        'bfz', 'bgb', 'bgc', 'bgd', 'bgf', 'bgg', 'bgh', 'bgj', 'bgk', 'bgm', 'bgn', 'bgp', 
        'bgq', 'bgs', 'bgt', 'bgv', 'bgx', 'bgz', 'bhb', 'bhc', 'bhf', 'bhh', 'bhj', 'bhk', 
        'bhl', 'bhm', 'bhn', 'bhq', 'bhs', 'bht', 'bhv', 'bhw', 'bhx', 'bhz', 'bjb', 'bjc', 
        'bjd', 'bjf', 'bjg', 'bjh', 'bjj', 'bjk', 'bjl', 'bjm', 'bjn', 'bjp', 'bjq', 'bjt', 
        'bjv', 'bjw', 'bjx', 'bjy', 'bjz', 'bkd', 'bkf', 'bkj', 'bkk', 'bkm', 'bkn', 'bko', 
        'bkq', 'bkr', 'bkv', 'bkw', 'bkx', 'bky', 'bkz', 'blb', 'blc', 'blf', 'blg', 'blh', 
        'blj', 'bll', 'blp', 'blq', 'blr', 'blt', 'blw', 'blx', 'blz', 'bmb', 'bmc', 'bmd', 
        'bmf', 'bmg', 'bmj', 'bmk', 'bml', 'bmm', 'bmn', 'bmp', 'bmq', 'bmr', 'bmt', 'bmv', 
        'bmw', 'bmx', 'bmz', 'bnb', 'bnc', 'bng', 'bnh', 'bnj', 'bnk', 'bnl', 'bnm', 'bnn', 
        'bnp', 'bnq', 'bnr', 'bns', 'bnt', 'bnv', 'bnw', 'bnx', 'bny', 'bnz', 'bpb', 'bpc', 
        'bpd', 'bpf', 'bpg', 'bpj', 'bpk', 'bpm', 'bpn', 'bpp', 'bpq', 'bpv', 'bpw', 'bpx', 
        'bpz', 'bqa', 'bqb', 'bqc', 'bqd', 'bqe', 'bqf', 'bqg', 'bqh', 'bqi', 'bqj', 'bqk', 
        'bql', 'bqm', 'bqn', 'bqo', 'bqp', 'bqq', 'bqr', 'bqs', 'bqt', 'bqv', 'bqw', 'bqx', 
        'bqy', 'bqz', 'brb', 'brc', 'brf', 'brg', 'brj', 'brk', 'brm', 'brp', 'brq', 'brs', 
        'brt', 'brv', 'brw', 'brx', 'brz', 'bsg', 'bsj', 'bsr', 'bsw', 'bsx', 'bsz', 'btb', 
        'btc', 'btd', 'btg', 'btj', 'btk', 'btn', 'btp', 'btq', 'btt', 'btv', 'btx', 'btz', 
        'buw', 'bvb', 'bvc', 'bvd', 'bvf', 'bvg', 'bvh', 'bvj', 'bvk', 'bvl', 'bvm', 'bvn', 
        'bvp', 'bvq', 'bvr', 'bvs', 'bvu', 'bvv', 'bvw', 'bvx', 'bvy', 'bvz', 'bwb', 'bwc', 
        'bwd', 'bwf', 'bwg', 'bwj', 'bwk', 'bwl', 'bwm', 'bwn', 'bwp', 'bwq', 'bws', 'bwt', 
        'bwu', 'bwv', 'bww', 'bwx', 'bwy', 'bwz', 'bxa', 'bxb', 'bxc', 'bxd', 'bxf', 'bxg', 
        'bxh', 'bxi', 'bxj', 'bxk', 'bxl', 'bxm', 'bxn', 'bxo', 'bxp', 'bxq', 'bxr', 'bxt', 
        'bxu', 'bxv', 'bxw', 'bxx', 'bxy', 'bxz', 'byj', 'byk', 'byq', 'byv', 'bza', 'bzb', 
        'bzc', 'bzd', 'bzf', 'bzg', 'bzj', 'bzk', 'bzl', 'bzm', 'bzn', 'bzp', 'bzq', 'bzr', 
        'bzs', 'bzt', 'bzv', 'bzw', 'bzx', 'bzz', 'cbb', 'cbc', 'cbd', 'cbf', 'cbg', 'cbh', 
        'cbj', 'cbk', 'cbp', 'cbq', 'cbs', 'cbt', 'cbv', 'cbw', 'cbx', 'cby', 'cbz', 'ccb', 
        'ccd', 'ccf', 'ccg', 'ccj', 'ccn', 'ccp', 'ccq', 'ccs', 'ccv', 'ccx', 'ccz', 'cdb', 
        'cdc', 'cdd', 'cdh', 'cdj', 'cdk', 'cdl', 'cdm', 'cdn', 'cdp', 'cdq', 'cds', 'cdt', 
        'cdv', 'cdw', 'cdx', 'cdz', 'cex', 'cfb', 'cfc', 'cfe', 'cff', 'cfg', 'cfj', 'cfk', 
        'cfn', 'cfp', 'cfq', 'cfr', 'cft', 'cfv', 'cfw', 'cfx', 'cfy', 'cfz', 'cga', 'cgb', 
        'cgc', 'cgd', 'cgf', 'cgg', 'cgh', 'cgj', 'cgk', 'cgl', 'cgn', 'cgp', 'cgq', 'cgt', 
        'cgu', 'cgv', 'cgw', 'cgx', 'cgz', 'chq', 'chx', 'cih', 'cik', 'ciy', 'cja', 'cjb', 
        'cjc', 'cjd', 'cje', 'cjf', 'cjg', 'cjh', 'cji', 'cjj', 'cjk', 'cjl', 'cjm', 'cjn', 
        'cjo', 'cjp', 'cjq', 'cjr', 'cjs', 'cjt', 'cju', 'cjv', 'cjw', 'cjx', 'cjy', 'cjz', 
        'ckz', 'clb', 'cld', 'clf', 'clg', 'clh', 'clj', 'cll', 'clm', 'clp', 'clq', 'cls', 
        'clt', 'clv', 'clw', 'clx', 'clz', 'cmb', 'cmc', 'cmf', 'cmg', 'cmh', 'cmj', 'cmk', 
        'cmm', 'cmp', 'cmq', 'cmr', 'cms', 'cmt', 'cmv', 'cmw', 'cmx', 'cmz', 'cnb', 'cnc', 
        'cnd', 'cnf', 'cng', 'cnh', 'cnj', 'cnk', 'cnl', 'cnm', 'cnn', 'cnp', 'cnq', 'cnr', 
        'cns', 'cnv', 'cnw', 'cnx', 'cny', 'cnz', 'cpb', 'cpc', 'cpf', 'cpg', 'cpj', 'cpk', 
        'cpp', 'cpq', 'cpv', 'cpw', 'cpx', 'cpy', 'cpz', 'cqa', 'cqb', 'cqc', 'cqd', 'cqe', 
        'cqf', 'cqg', 'cqh', 'cqi', 'cqj', 'cqk', 'cql', 'cqm', 'cqn', 'cqo', 'cqp', 'cqq', 
        'cqr', 'cqs', 'cqt', 'cqv', 'cqw', 'cqx', 'cqy', 'cqz', 'crb', 'crd', 'crg', 'crh', 
        'crj', 'crk', 'crm', 'crq', 'crr', 'crv', 'crx', 'csb', 'csd', 'csf', 'csg', 'csj', 
        'csq', 'csr', 'css', 'csu', 'csv', 'csx', 'csz', 'ctb', 'ctj', 'ctq', 'ctv', 'ctx', 
        'cuh', 'cuq', 'cuw', 'cux', 'cva', 'cvb', 'cvc', 'cvd', 'cve', 'cvf', 'cvg', 'cvh', 
        'cvi', 'cvj', 'cvk', 'cvl', 'cvm', 'cvn', 'cvo', 'cvp', 'cvq', 'cvs', 'cvt', 'cvu', 
        'cvv', 'cvw', 'cvx', 'cvy', 'cvz', 'cwb', 'cwc', 'cwd', 'cwf', 'cwg', 'cwh', 'cwj', 
        'cwk', 'cwl', 'cwn', 'cwp', 'cwq', 'cwu', 'cwv', 'cww', 'cwx', 'cwy', 'cwz', 'cxa', 
        'cxb', 'cxc', 'cxd', 'cxe', 'cxf', 'cxg', 'cxh', 'cxi', 'cxj', 'cxk', 'cxl', 'cxm', 
        'cxn', 'cxp', 'cxq', 'cxr', 'cxs', 'cxt', 'cxu', 'cxv', 'cxw', 'cxx', 'cxy', 'cxz', 
        'cyf', 'cyj', 'cyq', 'cyv', 'cyy', 'czb', 'czc', 'czd', 'czf', 'czg', 'czh', 'czj', 
        'czk', 'czl', 'czm', 'czn', 'czo', 'czp', 'czq', 'czr', 'czs', 'czt', 'czu', 'czv', 
        'czw', 'czx', 'czy', 'czz', 'dbb', 'dbc', 'dbd', 'dbf', 'dbg', 'dbj', 'dbn', 'dbp', 
        'dbq', 'dbs', 'dbt', 'dbv', 'dbw', 'dbx', 'dbz', 'dcc', 'dcd', 'dcf', 'dcg', 'dci', 
        'dcj', 'dck', 'dcm', 'dcn', 'dcp', 'dcq', 'dcs', 'dct', 'dcv', 'dcw', 'dcx', 'dcz', 
        'ddc', 'ddg', 'ddj', 'ddk', 'ddp', 'ddq', 'ddv', 'ddw', 'ddx', 'ddz', 'dfb', 'dfc', 
        'dfd', 'dfg', 'dfh', 'dfj', 'dfk', 'dfm', 'dfn', 'dfp', 'dfq', 'dfs', 'dfv', 'dfw', 
        'dfx', 'dfy', 'dfz', 'dgb', 'dgc', 'dgd', 'dgf', 'dgg', 'dgj', 'dgn', 'dgp', 'dgq', 
        'dgt', 'dgv', 'dgx', 'dgz', 'dhb', 'dhc', 'dhd', 'dhf', 'dhg', 'dhh', 'dhk', 'dhl', 
        'dhm', 'dhn', 'dhq', 'dht', 'dhw', 'dhx', 'dhz', 'djb', 'djc', 'djd', 'djf', 'djg', 
        'djh', 'djj', 'djk', 'djl', 'djm', 'djn', 'djp', 'djq', 'djr', 'djs', 'djv', 'djw', 
        'djx', 'djz', 'dkb', 'dkc', 'dkd', 'dkh', 'dkj', 'dkk', 'dkp', 'dkq', 'dkr', 'dkt', 
        'dku', 'dkv', 'dkw', 'dkx', 'dky', 'dkz', 'dlb', 'dlf', 'dlg', 'dlh', 'dlj', 'dlk', 
        'dll', 'dlm', 'dln', 'dlp', 'dlq', 'dlt', 'dlw', 'dlx', 'dlz', 'dmb', 'dmc', 'dmd', 
        'dmf', 'dmg', 'dmh', 'dmj', 'dmk', 'dml', 'dmm', 'dmn', 'dmq', 'dms', 'dmt', 'dmv', 
        'dmw', 'dmx', 'dmy', 'dmz', 'dnb', 'dnd', 'dnf', 'dng', 'dnh', 'dnj', 'dnk', 'dnm', 
        'dnn', 'dnp', 'dnq', 'dnr', 'dns', 'dnv', 'dnw', 'dnx', 'dnz', 'dpb', 'dpc', 'dpd', 
        'dpf', 'dpg', 'dpj', 'dpk', 'dpm', 'dpn', 'dpp', 'dpq', 'dps', 'dpv', 'dpw', 'dpx', 
        'dpy', 'dpz', 'dqa', 'dqb', 'dqc', 'dqd', 'dqe', 'dqf', 'dqg', 'dqh', 'dqi', 'dqj', 
        'dqk', 'dql', 'dqm', 'dqn', 'dqo', 'dqp', 'dqq', 'dqs', 'dqt', 'dqv', 'dqw', 'dqx', 
        'dqy', 'dqz', 'drb', 'drf', 'drg', 'drh', 'drj', 'drk', 'drl', 'drn', 'drp', 'drq', 
        'drr', 'drs', 'drt', 'drv', 'drw', 'drx', 'drz', 'dsd', 'dsg', 'dsj', 'dss', 'dsv', 
        'dsx', 'dsz', 'dtb', 'dtc', 'dtf', 'dtg', 'dtj', 'dtk', 'dtm', 'dtn', 'dtp', 'dtq', 
        'dtt', 'dtv', 'dtw', 'dtx', 'dtz', 'duw', 'dvb', 'dvc', 'dvd', 'dvf', 'dvg', 'dvh', 
        'dvj', 'dvk', 'dvl', 'dvm', 'dvn', 'dvp', 'dvq', 'dvr', 'dvs', 'dvu', 'dvv', 'dvw', 
        'dvx', 'dvy', 'dvz', 'dwb', 'dwc', 'dwd', 'dwf', 'dwg', 'dwj', 'dwk', 'dwm', 'dwn', 
        'dwp', 'dwq', 'dws', 'dwv', 'dww', 'dwx', 'dwz', 'dxa', 'dxb', 'dxc', 'dxd', 'dxe', 
        'dxf', 'dxg', 'dxh', 'dxi', 'dxj', 'dxk', 'dxl', 'dxm', 'dxn', 'dxo', 'dxp', 'dxq', 
        'dxr', 'dxs', 'dxu', 'dxv', 'dxw', 'dxx', 'dxy', 'dxz', 'dyj', 'dyq', 'dyy', 'dyz', 
        'dzb', 'dzc', 'dzd', 'dzf', 'dzg', 'dzj', 'dzk', 'dzl', 'dzm', 'dzn', 'dzp', 'dzq', 
        'dzr', 'dzs', 'dzt', 'dzv', 'dzw', 'dzx', 'dzy', 'dzz', 'eaj', 'ebj', 'ebn', 'ebp', 
        'ebq', 'ebv', 'ebx', 'ebz', 'ecf', 'ecj', 'ecv', 'ecx', 'edv', 'edx', 'edz', 'efj', 
        'efk', 'efq', 'efv', 'efx', 'egc', 'egj', 'egv', 'egx', 'egz', 'ehc', 'ehd', 'ehf', 
        'ehh', 'ehj', 'ehp', 'ehq', 'ehv', 'ehx', 'ehz', 'eiq', 'eiw', 'ejb', 'ejc', 'ejf', 
        'ejg', 'ejh', 'ejj', 'ejk', 'ejl', 'ejm', 'ejn', 'ejp', 'ejq', 'ejr', 'ejs', 'ejt', 
        'ejv', 'ejw', 'ejx', 'ejy', 'ejz', 'ekg', 'ekj', 'ekq', 'ekv', 'ekx', 'ekz', 'elx', 
        'emk', 'emq', 'emx', 'enx', 'eoj', 'eoq', 'epj', 'epv', 'epx', 'epz', 'eqa', 'eqb', 
        'eqc', 'eqg', 'eqh', 'eqi', 'eqj', 'eqk', 'eql', 'eqm', 'eqn', 'eqo', 'eqs', 'eqt', 
        'eqv', 'eqx', 'eqy', 'eqz', 'esj', 'esx', 'etq', 'etx', 'euj', 'euq', 'euu', 'euy', 
        'evb', 'evd', 'evf', 'evh', 'evj', 'evk', 'evp', 'evq', 'evt', 'evx', 'ewj', 'ewq', 
        'ewv', 'ewx', 'ewz', 'exb', 'exj', 'exk', 'exv', 'exw', 'eyq', 'eyz', 'ezf', 'ezj', 
        'ezs', 'ezt', 'ezw', 'ezx', 'fbb', 'fbc', 'fbd', 'fbf', 'fbg', 'fbh', 'fbj', 'fbk', 
        'fbm', 'fbn', 'fbp', 'fbq', 'fbs', 'fbt', 'fbv', 'fbw', 'fbx', 'fby', 'fbz', 'fcb', 
        'fcc', 'fcd', 'fce', 'fcf', 'fcg', 'fcj', 'fck', 'fcl', 'fcm', 'fcn', 'fcq', 'fct', 
        'fcv', 'fcw', 'fcx', 'fcz', 'fdb', 'fdc', 'fdd', 'fdf', 'fdg', 'fdh', 'fdj', 'fdk', 
        'fdl', 'fdm', 'fdp', 'fdq', 'fdr', 'fds', 'fdv', 'fdw', 'fdx', 'fdy', 'fdz', 'fej', 
        'feq', 'fff', 'ffj', 'ffq', 'ffv', 'ffx', 'ffz', 'fgb', 'fgc', 'fgd', 'fgf', 'fgg', 
        'fgj', 'fgk', 'fgl', 'fgm', 'fgp', 'fgq', 'fgs', 'fgt', 'fgu', 'fgv', 'fgw', 'fgx', 
        'fgy', 'fgz', 'fhb', 'fhc', 'fhd', 'fhf', 'fhg', 'fhh', 'fhi', 'fhj', 'fhk', 'fhl', 
        'fhm', 'fhn', 'fhp', 'fhq', 'fhs', 'fht', 'fhu', 'fhv', 'fhw', 'fhx', 'fhz', 'fih', 
        'fiw', 'fjb', 'fjc', 'fjd', 'fjf', 'fjg', 'fjh', 'fji', 'fjj', 'fjk', 'fjl', 'fjm', 
        'fjn', 'fjp', 'fjq', 'fjr', 'fjs', 'fjt', 'fju', 'fjv', 'fjw', 'fjx', 'fjy', 'fjz', 
        'fkb', 'fkc', 'fkd', 'fkf', 'fkg', 'fkh', 'fkj', 'fkk', 'fkm', 'fkn', 'fko', 'fkp', 
        'fkq', 'fkr', 'fks', 'fkt', 'fku', 'fkv', 'fkw', 'fkx', 'fkz', 'flf', 'flg', 'flj', 
        'flk', 'flm', 'flp', 'flq', 'fls', 'flt', 'flv', 'flw', 'flx', 'flz', 'fmb', 'fmc', 
        'fmd', 'fmf', 'fmg', 'fmh', 'fmi', 'fmj', 'fmk', 'fml', 'fmm', 'fmn', 'fmp', 'fmq', 
        'fmr', 'fms', 'fmv', 'fmw', 'fmx', 'fmy', 'fmz', 'fnb', 'fnc', 'fnd', 'fnf', 'fng', 
        'fnh', 'fnj', 'fnk', 'fnl', 'fnm', 'fnn', 'fno', 'fnp', 'fnq', 'fnr', 'fns', 'fnt', 
        'fnv', 'fnw', 'fnx', 'fnz', 'foj', 'foq', 'fpb', 'fpc', 'fpd', 'fpf', 'fpg', 'fpj', 
        'fpk', 'fpn', 'fpp', 'fpq', 'fpt', 'fpu', 'fpv', 'fpw', 'fpx', 'fpy', 'fpz', 'fqa', 
        'fqb', 'fqc', 'fqd', 'fqe', 'fqf', 'fqg', 'fqh', 'fqi', 'fqj', 'fqk', 'fql', 'fqm', 
        'fqn', 'fqo', 'fqp', 'fqq', 'fqr', 'fqs', 'fqt', 'fqu', 'fqv', 'fqw', 'fqx', 'fqy', 
        'fqz', 'frb', 'frc', 'frf', 'frg', 'frh', 'frj', 'frk', 'frl', 'frm', 'frn', 'frp', 
        'frq', 'frr', 'frv', 'frx', 'frz', 'fsd', 'fsf', 'fsg', 'fsj', 'fsl', 'fsn', 'fsq', 
        'fsr', 'fss', 'fsv', 'fsw', 'fsx', 'fsy', 'fsz', 'ftj', 'ftk', 'ftq', 'ftv', 'ftx', 
        'ftz', 'fuk', 'fuo', 'fup', 'fuq', 'fuu', 'fuw', 'fux', 'fva', 'fvb', 'fvc', 'fvd', 
        'fvf', 'fvg', 'fvh', 'fvi', 'fvj', 'fvk', 'fvl', 'fvm', 'fvn', 'fvo', 'fvp', 'fvq', 
        'fvr', 'fvs', 'fvt', 'fvu', 'fvv', 'fvw', 'fvx', 'fvy', 'fvz', 'fwb', 'fwc', 'fwf', 
        'fwg', 'fwh', 'fwj', 'fwk', 'fwl', 'fwm', 'fwn', 'fwp', 'fwq', 'fwr', 'fws', 'fwt', 
        'fwu', 'fwv', 'fww', 'fwx', 'fwy', 'fwz', 'fxa', 'fxb', 'fxc', 'fxd', 'fxe', 'fxf', 
        'fxg', 'fxh', 'fxi', 'fxj', 'fxk', 'fxl', 'fxm', 'fxn', 'fxo', 'fxp', 'fxq', 'fxr', 
        'fxs', 'fxt', 'fxu', 'fxv', 'fxw', 'fxx', 'fxy', 'fxz', 'fya', 'fyb', 'fyg', 'fyh', 
        'fyj', 'fyn', 'fyp', 'fyq', 'fyu', 'fyv', 'fyx', 'fyy', 'fyz', 'fza', 'fzb', 'fzc', 
        'fzd', 'fzf', 'fzg', 'fzh', 'fzj', 'fzk', 'fzl', 'fzm', 'fzn', 'fzo', 'fzp', 'fzq', 
        'fzr', 'fzs', 'fzt', 'fzu', 'fzv', 'fzw', 'fzx', 'fzy', 'fzz', 'gaq', 'gax', 'gbb', 
        'gbc', 'gbd', 'gbf', 'gbg', 'gbh', 'gbj', 'gbk', 'gbm', 'gbn', 'gbp', 'gbq', 'gbs', 
        'gbt', 'gbv', 'gbw', 'gbx', 'gbz', 'gcb', 'gcc', 'gce', 'gcf', 'gcg', 'gci', 'gcj', 
        'gck', 'gcm', 'gcn', 'gcp', 'gcq', 'gcs', 'gct', 'gcv', 'gcw', 'gcx', 'gcz', 'gdb', 
        'gdc', 'gdd', 'gdf', 'gdg', 'gdh', 'gdj', 'gdk', 'gdl', 'gdm', 'gdn', 'gdp', 'gdq', 
        'gdt', 'gdv', 'gdw', 'gdx', 'gdz', 'gej', 'geq', 'gex', 'gfb', 'gfc', 'gfd', 'gff', 
        'gfg', 'gfh', 'gfj', 'gfk', 'gfm', 'gfn', 'gfp', 'gfq', 'gfs', 'gft', 'gfv', 'gfw', 
        'gfx', 'gfy', 'gfz', 'ggg', 'ggj', 'ggk', 'ggq', 'ggt', 'ggv', 'ggx', 'ggz', 'ghq', 
        'ghx', 'giq', 'giw', 'gix', 'giy', 'gjb', 'gjc', 'gjd', 'gjf', 'gjg', 'gjh', 'gji', 
        'gjj', 'gjk', 'gjl', 'gjm', 'gjn', 'gjo', 'gjp', 'gjq', 'gjr', 'gjs', 'gjt', 'gjv', 
        'gjw', 'gjx', 'gjy', 'gjz', 'gkb', 'gkc', 'gkd', 'gkf', 'gkg', 'gkj', 'gkk', 'gkm', 
        'gkp', 'gkq', 'gks', 'gkt', 'gku', 'gkv', 'gkw', 'gkx', 'gky', 'gkz', 'glc', 'glf', 
        'glg', 'glh', 'glj', 'glk', 'gll', 'gln', 'glp', 'glq', 'glr', 'gls', 'glv', 'glw', 
        'glx', 'glz', 'gmb', 'gmc', 'gmd', 'gmf', 'gmg', 'gmj', 'gmk', 'gmm', 'gmn', 'gmp', 
        'gmq', 'gmr', 'gmv', 'gmw', 'gmx', 'gmz', 'gng', 'gnj', 'gnk', 'gnq', 'gnv', 'gnx', 
        'gnz', 'goj', 'gpb', 'gpf', 'gpg', 'gpj', 'gpk', 'gpn', 'gpp', 'gpq', 'gpt', 'gpv', 
        'gpw', 'gpx', 'gpy', 'gpz', 'gqa', 'gqb', 'gqc', 'gqd', 'gqe', 'gqf', 'gqg', 'gqh', 
        'gqi', 'gqj', 'gqk', 'gql', 'gqm', 'gqn', 'gqo', 'gqp', 'gqq', 'gqr', 'gqs', 'gqu', 
        'gqv', 'gqw', 'gqx', 'gqy', 'gqz', 'grb', 'grc', 'grg', 'grh', 'grj', 'grk', 'grl', 
        'grm', 'grq', 'grt', 'grv', 'grw', 'grz', 'gsj', 'gsq', 'gsr', 'gss', 'gsv', 'gsx', 
        'gsz', 'gtf', 'gtg', 'gtj', 'gtk', 'gtl', 'gtm', 'gtn', 'gtp', 'gtq', 'gts', 'gtv', 
        'gtw', 'gtx', 'guq', 'guu', 'guw', 'gux', 'gvb', 'gvc', 'gvd', 'gve', 'gvf', 'gvg', 
        'gvh', 'gvi', 'gvj', 'gvk', 'gvl', 'gvm', 'gvo', 'gvp', 'gvq', 'gvr', 'gvs', 'gvt', 
        'gvu', 'gvv', 'gvw', 'gvx', 'gvy', 'gvz', 'gwb', 'gwc', 'gwd', 'gwf', 'gwg', 'gwj', 
        'gwk', 'gwl', 'gwm', 'gwn', 'gwp', 'gwq', 'gws', 'gwt', 'gwv', 'gww', 'gwx', 'gwz', 
        'gxa', 'gxb', 'gxc', 'gxd', 'gxe', 'gxf', 'gxg', 'gxh', 'gxi', 'gxj', 'gxk', 'gxl', 
        'gxm', 'gxn', 'gxo', 'gxp', 'gxq', 'gxr', 'gxs', 'gxt', 'gxu', 'gxv', 'gxw', 'gxx', 
        'gxy', 'gxz', 'gyf', 'gyh', 'gyj', 'gyk', 'gyq', 'gyu', 'gyx', 'gyy', 'gzb', 'gzc', 
        'gzd', 'gze', 'gzf', 'gzg', 'gzh', 'gzi', 'gzj', 'gzk', 'gzl', 'gzm', 'gzn', 'gzo', 
        'gzp', 'gzq', 'gzr', 'gzs', 'gzt', 'gzu', 'gzv', 'gzx', 'gzy', 'gzz', 'hbb', 'hbc', 
        'hbd', 'hbf', 'hbg', 'hbh', 'hbj', 'hbk', 'hbm', 'hbp', 'hbq', 'hbs', 'hbt', 'hbv', 
        'hbw', 'hbx', 'hbz', 'hcc', 'hcd', 'hce', 'hcg', 'hcj', 'hck', 'hcm', 'hcn', 'hcp', 
        'hcq', 'hcs', 'hct', 'hcv', 'hcw', 'hcx', 'hcy', 'hcz', 'hdc', 'hdd', 'hdf', 'hdg', 
        'hdh', 'hdj', 'hdm', 'hdn', 'hdp', 'hds', 'hdt', 'hdv', 'hdx', 'hdy', 'hdz', 'hfb', 
        'hfc', 'hfd', 'hff', 'hfg', 'hfh', 'hfj', 'hfk', 'hfm', 'hfn', 'hfp', 'hfq', 'hft', 
        'hfv', 'hfw', 'hfx', 'hfy', 'hfz', 'hgb', 'hgc', 'hgd', 'hgf', 'hgg', 'hgh', 'hgj', 
        'hgk', 'hgn', 'hgp', 'hgq', 'hgs', 'hgv', 'hgx', 'hgy', 'hgz', 'hhb', 'hhc', 'hhf', 
        'hhg', 'hhh', 'hhj', 'hhk', 'hhl', 'hhm', 'hhn', 'hhp', 'hhq', 'hhr', 'hhs', 'hht', 
        'hhv', 'hhw', 'hhx', 'hhz', 'hjb', 'hjc', 'hjd', 'hjf', 'hjg', 'hjh', 'hjj', 'hjk', 
        'hjl', 'hjm', 'hjp', 'hjq', 'hjr', 'hjs', 'hjt', 'hju', 'hjv', 'hjw', 'hjx', 'hjy', 
        'hjz', 'hkb', 'hkc', 'hkd', 'hkg', 'hkj', 'hkk', 'hkl', 'hkm', 'hkp', 'hkq', 'hkr', 
        'hks', 'hkt', 'hkv', 'hkw', 'hkx', 'hkz', 'hlc', 'hlf', 'hlg', 'hlj', 'hlk', 'hlm', 
        'hln', 'hlp', 'hlv', 'hlx', 'hlz', 'hmb', 'hmc', 'hmd', 'hmf', 'hmh', 'hmj', 'hmk', 
        'hmq', 'hmr', 'hmt', 'hmv', 'hmw', 'hmx', 'hmz', 'hnc', 'hng', 'hnj', 'hnp', 'hnq', 
        'hnr', 'hnt', 'hnv', 'hnw', 'hnx', 'hnz', 'hpb', 'hpc', 'hpd', 'hpf', 'hpg', 'hpj', 
        'hpk', 'hpm', 'hpn', 'hpp', 'hpq', 'hpv', 'hpw', 'hpx', 'hpy', 'hpz', 'hqa', 'hqb', 
        'hqc', 'hqd', 'hqe', 'hqf', 'hqg', 'hqh', 'hqi', 'hqj', 'hqk', 'hql', 'hqm', 'hqn', 
        'hqo', 'hqp', 'hqq', 'hqr', 'hqs', 'hqt', 'hqv', 'hqw', 'hqx', 'hqy', 'hqz', 'hrc', 
        'hrf', 'hrg', 'hrh', 'hrj', 'hrk', 'hrn', 'hrp', 'hrq', 'hrt', 'hrv', 'hrx', 'hsb', 
        'hsf', 'hsj', 'hsq', 'hsr', 'hss', 'hsv', 'hsx', 'hsz', 'htq', 'htx', 'htz', 'huq', 
        'huw', 'hvb', 'hvc', 'hvd', 'hvf', 'hvg', 'hvj', 'hvk', 'hvl', 'hvm', 'hvn', 'hvo', 
        'hvp', 'hvq', 'hvs', 'hvt', 'hvu', 'hvv', 'hvw', 'hvx', 'hvz', 'hwb', 'hwc', 'hwd', 
        'hwf', 'hwg', 'hwj', 'hwk', 'hwl', 'hwm', 'hwn', 'hwp', 'hwq', 'hws', 'hwv', 'hww', 
        'hwx', 'hwz', 'hxa', 'hxb', 'hxc', 'hxd', 'hxe', 'hxf', 'hxg', 'hxh', 'hxi', 'hxj', 
        'hxk', 'hxl', 'hxm', 'hxn', 'hxo', 'hxp', 'hxq', 'hxr', 'hxs', 'hxt', 'hxu', 'hxv', 
        'hxw', 'hxx', 'hxy', 'hxz', 'hyj', 'hyq', 'hzb', 'hzc', 'hzd', 'hzf', 'hzg', 'hzh', 
        'hzi', 'hzj', 'hzk', 'hzl', 'hzm', 'hzn', 'hzp', 'hzq', 'hzr', 'hzs', 'hzt', 'hzu', 
        'hzv', 'hzw', 'hzx', 'hzz', 'iay', 'ibf', 'ibj', 'ibp', 'ibq', 'ibt', 'ibv', 'ibx', 
        'icj', 'icv', 'icx', 'idq', 'idx', 'ieo', 'ifc', 'ifg', 'ifh', 'ifj', 'ifk', 'ifm', 
        'ifp', 'ifq', 'ifv', 'ifw', 'ifx', 'ifz', 'igc', 'igj', 'igk', 'igq', 'igv', 'igx', 
        'ihb', 'ihc', 'ihg', 'ihh', 'ihj', 'ihk', 'ihm', 'ihq', 'ihv', 'ihw', 'ihx', 'ihz', 
        'iib', 'iig', 'iih', 'iij', 'iiq', 'iir', 'iiv', 'iix', 'iiy', 'ijc', 'ijf', 'ijg', 
        'ijp', 'ijq', 'ijs', 'ijt', 'ijx', 'ijy', 'ijz', 'ikb', 'ikc', 'ikf', 'ikg', 'ikj', 
        'ikm', 'ikp', 'ikq', 'ikx', 'ilx', 'imq', 'imx', 'ipq', 'ipv', 'ipx', 'iqb', 'iqc', 
        'iqd', 'iqe', 'iqf', 'iqg', 'iqi', 'iqj', 'iqk', 'iql', 'iqm', 'iqn', 'iqo', 'iqp', 
        'iqq', 'iqt', 'iqv', 'iqw', 'iqx', 'iqy', 'iqz', 'irx', 'isx', 'itq', 'itx', 'iuf', 
        'iuh', 'iui', 'iuo', 'iuw', 'iux', 'iuy', 'iuz', 'ivb', 'ivc', 'ivf', 'ivg', 'ivh', 
        'ivj', 'ivk', 'ivm', 'ivp', 'ivq', 'ivx', 'iwc', 'iwd', 'iwg', 'iwj', 'iwk', 'iwl', 
        'iwm', 'iwn', 'iwp', 'iwq', 'iwr', 'iws', 'iwt', 'iwv', 'iwx', 'iwz', 'ixc', 'ixj', 
        'ixk', 'ixq', 'ixr', 'ixv', 'ixx', 'ixz', 'iyb', 'iyc', 'iyd', 'iyf', 'iyg', 'iyh', 
        'iyj', 'iyk', 'iyl', 'iym', 'iyp', 'iyq', 'iyr', 'iys', 'iyt', 'iyv', 'iyw', 'iyx', 
        'iyy', 'iyz', 'izf', 'izh', 'izj', 'izq', 'izx', 'jaf', 'jbb', 'jbc', 'jbd', 'jbe', 
        'jbf', 'jbg', 'jbh', 'jbj', 'jbk', 'jbl', 'jbm', 'jbn', 'jbo', 'jbp', 'jbq', 'jbr', 
        'jbs', 'jbt', 'jbu', 'jbv', 'jbw', 'jbx', 'jby', 'jbz', 'jca', 'jcb', 'jcc', 'jcd', 
        'jce', 'jcf', 'jcg', 'jch', 'jci', 'jcj', 'jck', 'jcm', 'jcn', 'jco', 'jcp', 'jcq', 
        'jcr', 'jcs', 'jcu', 'jcv', 'jcw', 'jcx', 'jcy', 'jcz', 'jdb', 'jdc', 'jdd', 'jde', 
        'jdf', 'jdg', 'jdh', 'jdj', 'jdk', 'jdl', 'jdm', 'jdn', 'jdo', 'jdp', 'jdq', 'jdr', 
        'jdt', 'jdu', 'jdv', 'jdw', 'jdx', 'jdy', 'jdz', 'jey', 'jfa', 'jfb', 'jfc', 'jfd', 
        'jfe', 'jff', 'jfg', 'jfh', 'jfi', 'jfj', 'jfk', 'jfl', 'jfm', 'jfn', 'jfo', 'jfp', 
        'jfq', 'jfr', 'jfs', 'jft', 'jfu', 'jfv', 'jfw', 'jfx', 'jfy', 'jfz', 'jga', 'jgb', 
        'jgc', 'jgd', 'jgf', 'jgg', 'jgh', 'jgi', 'jgj', 'jgk', 'jgl', 'jgm', 'jgn', 'jgo', 
        'jgp', 'jgq', 'jgr', 'jgs', 'jgt', 'jgu', 'jgv', 'jgw', 'jgx', 'jgy', 'jgz', 'jhb', 
        'jhc', 'jhd', 'jhf', 'jhg', 'jhh', 'jhi', 'jhj', 'jhk', 'jhl', 'jhm', 'jhn', 'jhp', 
        'jhq', 'jhr', 'jhs', 'jht', 'jhw', 'jhx', 'jhy', 'jhz', 'jii', 'jij', 'jio', 'jiw', 
        'jiy', 'jjb', 'jjc', 'jjd', 'jjf', 'jjg', 'jjh', 'jjj', 'jjk', 'jjl', 'jjm', 'jjn', 
        'jjo', 'jjp', 'jjq', 'jjr', 'jjs', 'jjt', 'jju', 'jjv', 'jjw', 'jjx', 'jjy', 'jjz', 
        'jka', 'jkb', 'jkc', 'jkd', 'jke', 'jkf', 'jkg', 'jkh', 'jkj', 'jkk', 'jkl', 'jkm', 
        'jkn', 'jko', 'jkp', 'jkq', 'jkr', 'jkt', 'jku', 'jkv', 'jkw', 'jkx', 'jky', 'jkz', 
        'jla', 'jlb', 'jlc', 'jld', 'jle', 'jlf', 'jlg', 'jlh', 'jlj', 'jll', 'jlm', 'jln', 
        'jlo', 'jlp', 'jlq', 'jlr', 'jls', 'jlt', 'jlu', 'jlv', 'jlw', 'jlx', 'jly', 'jlz', 
        'jmb', 'jmc', 'jmd', 'jme', 'jmf', 'jmg', 'jmh', 'jmi', 'jmj', 'jmk', 'jml', 'jmm', 
        'jmn', 'jmo', 'jmp', 'jmq', 'jmr', 'jmt', 'jmu', 'jmv', 'jmw', 'jmx', 'jmy', 'jmz', 
        'jnb', 'jnc', 'jne', 'jnf', 'jni', 'jnj', 'jnk', 'jnl', 'jnm', 'jnn', 'jnp', 'jnq', 
        'jnr', 'jns', 'jnu', 'jnv', 'jnw', 'jnx', 'jny', 'jnz', 'joq', 'jox', 'jpa', 'jpb', 
        'jpc', 'jpd', 'jpe', 'jpf', 'jpg', 'jph', 'jpi', 'jpj', 'jpk', 'jpl', 'jpm', 'jpn', 
        'jpp', 'jpq', 'jpr', 'jps', 'jpt', 'jpv', 'jpw', 'jpx', 'jpy', 'jpz', 'jqa', 'jqb', 
        'jqc', 'jqd', 'jqe', 'jqf', 'jqg', 'jqh', 'jqi', 'jqj', 'jqk', 'jql', 'jqm', 'jqn', 
        'jqo', 'jqp', 'jqq', 'jqr', 'jqs', 'jqt', 'jqu', 'jqv', 'jqw', 'jqx', 'jqy', 'jqz', 
        'jrb', 'jrc', 'jrd', 'jrf', 'jrg', 'jrh', 'jrj', 'jrk', 'jrl', 'jrm', 'jrn', 'jro', 
        'jrp', 'jrq', 'jrr', 'jrs', 'jrt', 'jru', 'jrv', 'jrw', 'jrx', 'jry', 'jrz', 'jsa', 
        'jsb', 'jsd', 'jse', 'jsf', 'jsg', 'jsh', 'jsi', 'jsj', 'jsk', 'jsl', 'jsm', 'jsn', 
        'jso', 'jsp', 'jsq', 'jsr', 'jss', 'jst', 'jsu', 'jsv', 'jsw', 'jsx', 'jsy', 'jsz', 
        'jtb', 'jtc', 'jtd', 'jte', 'jtf', 'jtg', 'jth', 'jti', 'jtj', 'jtk', 'jtl', 'jtm', 
        'jtn', 'jto', 'jtp', 'jtq', 'jtr', 'jts', 'jtt', 'jtu', 'jtv', 'jtw', 'jtx', 'jty', 
        'jtz', 'juo', 'juq', 'juu', 'jva', 'jvb', 'jvc', 'jvd', 'jvf', 'jvg', 'jvh', 'jvi', 
        'jvj', 'jvk', 'jvl', 'jvm', 'jvn', 'jvo', 'jvp', 'jvq', 'jvr', 'jvs', 'jvt', 'jvu', 
        'jvv', 'jvw', 'jvx', 'jvy', 'jvz', 'jwb', 'jwc', 'jwd', 'jwe', 'jwf', 'jwg', 'jwh', 
        'jwi', 'jwj', 'jwk', 'jwl', 'jwm', 'jwn', 'jwp', 'jwq', 'jwr', 'jws', 'jwt', 'jwu', 
        'jwv', 'jww', 'jwx', 'jwy', 'jwz', 'jxa', 'jxb', 'jxc', 'jxd', 'jxe', 'jxf', 'jxg', 
        'jxh', 'jxi', 'jxj', 'jxk', 'jxl', 'jxm', 'jxn', 'jxo', 'jxp', 'jxq', 'jxr', 'jxs', 
        'jxt', 'jxu', 'jxv', 'jxw', 'jxx', 'jxy', 'jxz', 'jya', 'jyb', 'jyc', 'jyd', 'jye', 
        'jyf', 'jyg', 'jyh', 'jyi', 'jyj', 'jyk', 'jyo', 'jyp', 'jyq', 'jyr', 'jys', 'jyt', 
        'jyu', 'jyv', 'jyw', 'jyx', 'jyy', 'jyz', 'jza', 'jzb', 'jzc', 'jzd', 'jze', 'jzf', 
        'jzg', 'jzh', 'jzi', 'jzj', 'jzk', 'jzl', 'jzm', 'jzn', 'jzo', 'jzp', 'jzq', 'jzr', 
        'jzs', 'jzt', 'jzu', 'jzv', 'jzw', 'jzx', 'jzy', 'jzz', 'kaq', 'kbb', 'kbc', 'kbd', 
        'kbf', 'kbg', 'kbh', 'kbj', 'kbk', 'kbm', 'kbq', 'kbs', 'kbt', 'kbv', 'kbw', 'kbx', 
        'kby', 'kbz', 'kcb', 'kcc', 'kcd', 'kce', 'kcf', 'kcg', 'kcj', 'kck', 'kcm', 'kcn', 
        'kcp', 'kcq', 'kcs', 'kct', 'kcv', 'kcw', 'kcx', 'kcz', 'kdb', 'kdc', 'kdd', 'kdf', 
        'kdg', 'kdh', 'kdj', 'kdk', 'kdl', 'kdm', 'kdn', 'kdp', 'kdq', 'kds', 'kdt', 'kdu', 
        'kdv', 'kdw', 'kdx', 'kdy', 'kdz', 'keq', 'kez', 'kfb', 'kfc', 'kfd', 'kff', 'kfg', 
        'kfh', 'kfj', 'kfk', 'kfm', 'kfn', 'kfp', 'kfq', 'kfs', 'kft', 'kfv', 'kfw', 'kfx', 
        'kfy', 'kfz', 'kgb', 'kgc', 'kgg', 'kgh', 'kgj', 'kgk', 'kgl', 'kgm', 'kgn', 'kgp', 
        'kgq', 'kgt', 'kgv', 'kgw', 'kgx', 'kgy', 'kgz', 'khb', 'khc', 'khf', 'khg', 'khh', 
        'khj', 'khk', 'khq', 'khx', 'kig', 'kiq', 'kix', 'kjb', 'kjc', 'kjd', 'kjf', 'kjg', 
        'kjh', 'kji', 'kjj', 'kjk', 'kjl', 'kjm', 'kjn', 'kjp', 'kjq', 'kjr', 'kjs', 'kjt', 
        'kjv', 'kjw', 'kjx', 'kjy', 'kjz', 'kkb', 'kkc', 'kkd', 'kkf', 'kkg', 'kkj', 'kkk', 
        'kkm', 'kkp', 'kkq', 'kkr', 'kks', 'kkt', 'kkv', 'kkw', 'kkx', 'kkz', 'klb', 'klc', 
        'kld', 'klf', 'klg', 'klh', 'klj', 'klk', 'kll', 'klm', 'klp', 'klq', 'kls', 'klt', 
        'klw', 'klx', 'klz', 'kmb', 'kmc', 'kmd', 'kmf', 'kmg', 'kmh', 'kmj', 'kmk', 'kml', 
        'kmm', 'kmn', 'kmp', 'kmq', 'kmr', 'kms', 'kmt', 'kmw', 'kmx', 'kmy', 'kmz', 'knb', 
        'knc', 'knd', 'knf', 'knh', 'knj', 'knk', 'knl', 'knm', 'knn', 'knp', 'knq', 'knr', 
        'kns', 'knt', 'knv', 'knw', 'knx', 'knz', 'koq', 'kpb', 'kpd', 'kpf', 'kpg', 'kpj', 
        'kpk', 'kpm', 'kpn', 'kpp', 'kpq', 'kps', 'kpv', 'kpw', 'kpx', 'kpy', 'kpz', 'kqa', 
        'kqb', 'kqc', 'kqd', 'kqe', 'kqf', 'kqg', 'kqh', 'kqi', 'kqj', 'kqk', 'kql', 'kqm', 
        'kqn', 'kqo', 'kqp', 'kqq', 'kqr', 'kqs', 'kqt', 'kqv', 'kqw', 'kqx', 'kqy', 'kqz', 
        'krb', 'krc', 'krd', 'krf', 'krg', 'krh', 'krj', 'krl', 'krm', 'krp', 'krq', 'krr', 
        'krv', 'krw', 'krx', 'ksj', 'ksq', 'kss', 'ksx', 'ksz', 'ktb', 'ktc', 'ktd', 'ktf', 
        'ktj', 'ktk', 'ktl', 'ktm', 'ktn', 'ktp', 'ktq', 'ktv', 'ktx', 'kuq', 'kuu', 'kux', 
        'kuz', 'kvb', 'kvc', 'kvd', 'kvf', 'kvg', 'kvh', 'kvj', 'kvk', 'kvl', 'kvm', 'kvn', 
        'kvp', 'kvq', 'kvr', 'kvs', 'kvt', 'kvv', 'kvw', 'kvx', 'kvy', 'kvz', 'kwb', 'kwc', 
        'kwd', 'kwf', 'kwg', 'kwj', 'kwk', 'kwl', 'kwm', 'kwn', 'kwp', 'kwq', 'kws', 'kwt', 
        'kwv', 'kww', 'kwx', 'kwz', 'kxa', 'kxb', 'kxc', 'kxd', 'kxe', 'kxf', 'kxg', 'kxh', 
        'kxj', 'kxk', 'kxl', 'kxm', 'kxn', 'kxo', 'kxp', 'kxq', 'kxr', 'kxs', 'kxt', 'kxu', 
        'kxv', 'kxw', 'kxx', 'kxy', 'kxz', 'kyg', 'kyq', 'kyv', 'kyx', 'kyy', 'kyz', 'kzb', 
        'kzc', 'kzd', 'kze', 'kzf', 'kzg', 'kzh', 'kzi', 'kzj', 'kzk', 'kzl', 'kzm', 'kzn', 
        'kzo', 'kzp', 'kzq', 'kzr', 'kzs', 'kzt', 'kzu', 'kzv', 'kzw', 'kzx', 'kzy', 'kzz', 
        'lbb', 'lbc', 'lbd', 'lbg', 'lbh', 'lbj', 'lbk', 'lbm', 'lbn', 'lbp', 'lbq', 'lbt', 
        'lbv', 'lbx', 'lbz', 'lcb', 'lcc', 'lcf', 'lcj', 'lcn', 'lcp', 'lcq', 'lcv', 'lcx', 
        'lcz', 'ldj', 'ldv', 'ldz', 'lfj', 'lfq', 'lfv', 'lfx', 'lfz', 'lgb', 'lgc', 'lgd', 
        'lgf', 'lgg', 'lgk', 'lgm', 'lgn', 'lgp', 'lgq', 'lgs', 'lgv', 'lgw', 'lgx', 'lgz', 
        'lhc', 'lhf', 'lhg', 'lhh', 'lhj', 'lhk', 'lhl', 'lhm', 'lhn', 'lhp', 'lhq', 'lhr', 
        'lhs', 'lht', 'lhv', 'lhw', 'lhx', 'lhz', 'ljb', 'ljc', 'ljd', 'ljf', 'ljg', 'ljh', 
        'ljj', 'ljk', 'ljl', 'ljm', 'ljn', 'ljp', 'ljq', 'ljr', 'ljs', 'ljt', 'ljv', 'ljw', 
        'ljx', 'ljy', 'ljz', 'lkq', 'lkx', 'lkz', 'llx', 'llz', 'lmj', 'lmk', 'lmq', 'lmr', 
        'lmt', 'lmv', 'lmx', 'lmz', 'lnc', 'lnf', 'lnj', 'lnk', 'lnn', 'lnp', 'lnq', 'lnv', 
        'lnw', 'lnx', 'lny', 'lnz', 'lpc', 'lpd', 'lpg', 'lpj', 'lpk', 'lpp', 'lpq', 'lpv', 
        'lpx', 'lpz', 'lqa', 'lqb', 'lqc', 'lqd', 'lqe', 'lqf', 'lqh', 'lqi', 'lqj', 'lqk', 
        'lql', 'lqm', 'lqo', 'lqp', 'lqq', 'lqr', 'lqs', 'lqt', 'lqv', 'lqw', 'lqx', 'lqy', 
        'lqz', 'lrb', 'lrc', 'lrd', 'lrf', 'lrg', 'lrh', 'lrj', 'lrk', 'lrl', 'lrm', 'lrn', 
        'lrp', 'lrq', 'lrr', 'lrs', 'lrt', 'lrv', 'lrw', 'lrx', 'lrz', 'lsj', 'lsq', 'lsr', 
        'lsx', 'lsz', 'ltk', 'ltq', 'ltx', 'luu', 'lvb', 'lvc', 'lvf', 'lvg', 'lvh', 'lvj', 
        'lvk', 'lvl', 'lvm', 'lvn', 'lvp', 'lvq', 'lvr', 'lvt', 'lvw', 'lvx', 'lvz', 'lwb', 
        'lwc', 'lwd', 'lwf', 'lwg', 'lwj', 'lwk', 'lwn', 'lwq', 'lws', 'lwt', 'lwv', 'lww', 
        'lwx', 'lwy', 'lwz', 'lxa', 'lxb', 'lxc', 'lxd', 'lxf', 'lxg', 'lxh', 'lxi', 'lxj', 
        'lxk', 'lxl', 'lxm', 'lxn', 'lxo', 'lxp', 'lxq', 'lxr', 'lxs', 'lxt', 'lxu', 'lxv', 
        'lxw', 'lxz', 'lyj', 'lyq', 'lyy', 'lzc', 'lzd', 'lzg', 'lzj', 'lzk', 'lzl', 'lzm', 
        'lzn', 'lzp', 'lzq', 'lzr', 'lzs', 'lzt', 'lzu', 'lzv', 'lzw', 'lzx', 'lzz', 'mbg', 
        'mbj', 'mbq', 'mbv', 'mbx', 'mbz', 'mcb', 'mcj', 'mcm', 'mcq', 'mcs', 'mct', 'mcv', 
        'mcw', 'mcx', 'mcz', 'mdb', 'mdc', 'mdd', 'mdf', 'mdh', 'mdj', 'mdk', 'mdp', 'mdq', 
        'mdv', 'mdw', 'mdx', 'mdy', 'mdz', 'mfb', 'mfc', 'mff', 'mfh', 'mfj', 'mfk', 'mfm', 
        'mfn', 'mfp', 'mfq', 'mft', 'mfv', 'mfw', 'mfx', 'mfz', 'mgb', 'mgc', 'mgf', 'mgg', 
        'mgj', 'mgk', 'mgl', 'mgm', 'mgn', 'mgp', 'mgq', 'mgs', 'mgv', 'mgw', 'mgx', 'mgz', 
        'mhb', 'mhc', 'mhd', 'mhf', 'mhh', 'mhj', 'mhk', 'mhl', 'mhm', 'mhn', 'mhq', 'mhs', 
        'mht', 'mhv', 'mhw', 'mhx', 'mjb', 'mjc', 'mjd', 'mjf', 'mjg', 'mjh', 'mji', 'mjj', 
        'mjk', 'mjm', 'mjn', 'mjp', 'mjq', 'mjr', 'mjs', 'mjt', 'mjv', 'mjw', 'mjx', 'mjy', 
        'mjz', 'mkb', 'mkc', 'mkd', 'mkf', 'mkg', 'mkk', 'mkl', 'mkm', 'mkn', 'mkp', 'mkq', 
        'mkr', 'mkv', 'mkw', 'mkx', 'mkz', 'mlb', 'mlc', 'mld', 'mlf', 'mlg', 'mlh', 'mlj', 
        'mlk', 'mll', 'mlm', 'mln', 'mlp', 'mlq', 'mlr', 'mls', 'mlt', 'mlv', 'mlw', 'mlz', 
        'mmc', 'mmg', 'mmj', 'mmq', 'mmt', 'mmv', 'mmw', 'mmx', 'mmz', 'mnf', 'mnh', 'mnj', 
        'mnk', 'mnm', 'mnp', 'mnq', 'mnr', 'mnv', 'mnx', 'mnz', 'mpj', 'mpx', 'mpz', 'mqa', 
        'mqb', 'mqc', 'mqd', 'mqe', 'mqf', 'mqg', 'mqh', 'mqi', 'mqj', 'mqk', 'mql', 'mqm', 
        'mqn', 'mqo', 'mqp', 'mqq', 'mqr', 'mqs', 'mqt', 'mqv', 'mqw', 'mqx', 'mqy', 'mqz', 
        'mrb', 'mrc', 'mrd', 'mrf', 'mrh', 'mrj', 'mrk', 'mrl', 'mrm', 'mrn', 'mrq', 'mrt', 
        'mrv', 'mrw', 'mrz', 'msj', 'msn', 'msr', 'msv', 'msx', 'msz', 'mtb', 'mtc', 'mtf', 
        'mtj', 'mtk', 'mtp', 'mtq', 'mtt', 'mtv', 'mtw', 'mtz', 'muw', 'mvb', 'mvc', 'mvd', 
        'mvf', 'mvg', 'mvh', 'mvj', 'mvk', 'mvl', 'mvm', 'mvn', 'mvp', 'mvq', 'mvr', 'mvs', 
        'mvt', 'mvu', 'mvv', 'mvw', 'mvx', 'mvy', 'mvz', 'mwb', 'mwc', 'mwd', 'mwf', 'mwg', 
        'mwj', 'mwk', 'mwl', 'mwm', 'mwn', 'mwp', 'mwq', 'mwr', 'mws', 'mwt', 'mwu', 'mwv', 
        'mww', 'mwx', 'mwy', 'mwz', 'mxa', 'mxb', 'mxc', 'mxe', 'mxf', 'mxg', 'mxh', 'mxi', 
        'mxj', 'mxk', 'mxl', 'mxm', 'mxn', 'mxo', 'mxp', 'mxq', 'mxr', 'mxs', 'mxt', 'mxu', 
        'mxv', 'mxw', 'mxx', 'mxy', 'mxz', 'myf', 'myj', 'myq', 'myu', 'myv', 'myy', 'mzb', 
        'mzc', 'mzd', 'mzf', 'mzg', 'mzh', 'mzj', 'mzk', 'mzm', 'mzn', 'mzo', 'mzp', 'mzq', 
        'mzr', 'mzs', 'mzt', 'mzv', 'mzw', 'mzx', 'mzz', 'nbc', 'nbf', 'nbh', 'nbj', 'nbk', 
        'nbm', 'nbn', 'nbp', 'nbq', 'nbs', 'nbt', 'nbv', 'nbw', 'nbx', 'nbz', 'ncb', 'ncd', 
        'ncf', 'ncj', 'ncq', 'ncv', 'ncw', 'ncx', 'ncz', 'ndx', 'nfb', 'nfc', 'nfg', 'nfh', 
        'nfj', 'nfk', 'nfm', 'nfn', 'nfp', 'nfq', 'nfs', 'nft', 'nfv', 'nfw', 'nfx', 'nfz', 
        'ngq', 'ngv', 'ngx', 'ngz', 'nhb', 'nhc', 'nhd', 'nhf', 'nhg', 'nhh', 'nhj', 'nhk', 
        'nhl', 'nhm', 'nhp', 'nhq', 'nhr', 'nht', 'nhv', 'nhx', 'nhz', 'njb', 'njc', 'njd', 
        'njf', 'njg', 'njh', 'njj', 'njk', 'njl', 'njm', 'njn', 'njp', 'njq', 'njs', 'njt', 
        'njv', 'njw', 'njx', 'njz', 'nkj', 'nkq', 'nkv', 'nkx', 'nkz', 'nlb', 'nlc', 'nld', 
        'nlf', 'nlg', 'nlh', 'nlj', 'nlk', 'nll', 'nlm', 'nln', 'nlp', 'nlq', 'nlr', 'nls', 
        'nlv', 'nlw', 'nlx', 'nlz', 'nmb', 'nmc', 'nmd', 'nmf', 'nmg', 'nmh', 'nmj', 'nmk', 
        'nml', 'nmm', 'nmq', 'nmr', 'nms', 'nmt', 'nmv', 'nmw', 'nmx', 'nmz', 'nnb', 'nnd', 
        'nnf', 'nnj', 'nnp', 'nnq', 'nnr', 'nnt', 'nnv', 'nnx', 'nnz', 'npb', 'npc', 'npd', 
        'npg', 'npj', 'npm', 'npp', 'npq', 'npv', 'npw', 'npx', 'npz', 'nqa', 'nqb', 'nqc', 
        'nqd', 'nqe', 'nqf', 'nqg', 'nqh', 'nqj', 'nqk', 'nql', 'nqm', 'nqn', 'nqo', 'nqp', 
        'nqq', 'nqr', 'nqs', 'nqt', 'nqv', 'nqw', 'nqx', 'nqy', 'nqz', 'nrb', 'nrc', 'nrd', 
        'nrf', 'nrj', 'nrk', 'nrm', 'nrn', 'nrp', 'nrq', 'nrs', 'nrt', 'nrv', 'nrw', 'nrx', 
        'nrz', 'nsx', 'nsz', 'ntq', 'ntx', 'nuh', 'nuj', 'nuw', 'nvb', 'nvc', 'nvd', 'nvf', 
        'nvg', 'nvh', 'nvj', 'nvk', 'nvl', 'nvm', 'nvn', 'nvp', 'nvq', 'nvr', 'nvs', 'nvw', 
        'nvx', 'nvz', 'nwb', 'nwc', 'nwd', 'nwf', 'nwg', 'nwj', 'nwk', 'nwl', 'nwm', 'nwn', 
        'nwp', 'nwq', 'nws', 'nwt', 'nwu', 'nwv', 'nwx', 'nwz', 'nxa', 'nxb', 'nxc', 'nxd', 
        'nxf', 'nxg', 'nxh', 'nxj', 'nxk', 'nxn', 'nxo', 'nxp', 'nxq', 'nxu', 'nxv', 'nxx', 
        'nxy', 'nxz', 'nyj', 'nyq', 'nyy', 'nzc', 'nzf', 'nzg', 'nzj', 'nzl', 'nzm', 'nzn', 
        'nzq', 'nzr', 'nzv', 'nzw', 'nzx', 'nzz', 'oaa', 'oay', 'obq', 'obx', 'ocf', 'ocg', 
        'ocj', 'ocp', 'ocv', 'ocw', 'ocx', 'odq', 'odv', 'odx', 'oej', 'ofc', 'ofg', 'ofh', 
        'ofj', 'ofq', 'ofv', 'ofx', 'ofz', 'ogk', 'ogq', 'ogx', 'ogz', 'ohb', 'ohc', 'ohd', 
        'ohf', 'ohg', 'ohh', 'ohk', 'ohq', 'ohx', 'ohz', 'oij', 'oiq', 'oiu', 'oiw', 'ojb', 
        'ojc', 'ojf', 'ojg', 'ojh', 'ojj', 'ojl', 'ojm', 'ojn', 'ojq', 'ojr', 'ojs', 'ojt', 
        'ojv', 'ojw', 'ojx', 'ojy', 'ojz', 'okg', 'okq', 'okx', 'okz', 'omq', 'omx', 'ooq', 
        'opq', 'opx', 'opz', 'oqa', 'oqb', 'oqc', 'oqd', 'oqe', 'oqf', 'oqg', 'oqh', 'oqi', 
        'oqj', 'oqk', 'oql', 'oqm', 'oqn', 'oqo', 'oqp', 'oqq', 'oqr', 'oqs', 'oqt', 'oqv', 
        'oqw', 'oqx', 'oqy', 'oqz', 'orx', 'osd', 'osf', 'osv', 'osx', 'otv', 'ovb', 'ovd', 
        'ovf', 'ovg', 'ovh', 'ovj', 'ovm', 'ovq', 'ovw', 'ovx', 'ovz', 'owx', 'oxj', 'oxq', 
        'oxx', 'oxz', 'oyj', 'oyk', 'oyq', 'oyv', 'oyx', 'oyy', 'oyz', 'ozb', 'ozd', 'ozf', 
        'ozg', 'ozj', 'ozk', 'ozm', 'ozp', 'ozq', 'ozr', 'ozt', 'ozv', 'ozw', 'ozx', 'pbc', 
        'pbd', 'pbf', 'pbg', 'pbh', 'pbj', 'pbk', 'pbm', 'pbn', 'pbp', 'pbq', 'pbt', 'pbv', 
        'pbw', 'pbz', 'pcb', 'pcc', 'pcg', 'pcj', 'pck', 'pcn', 'pcp', 'pcq', 'pcs', 'pcv', 
        'pcw', 'pcx', 'pcz', 'pdb', 'pdc', 'pdd', 'pdf', 'pdg', 'pdh', 'pdj', 'pdk', 'pdm', 
        'pdp', 'pds', 'pdu', 'pdv', 'pdw', 'pdx', 'pdy', 'pdz', 'pfb', 'pfh', 'pfj', 'pfk', 
        'pfm', 'pfn', 'pfp', 'pfq', 'pft', 'pfv', 'pfw', 'pfy', 'pfz', 'pgb', 'pgc', 'pgd', 
        'pgf', 'pgg', 'pgh', 'pgj', 'pgk', 'pgm', 'pgp', 'pgq', 'pgs', 'pgt', 'pgv', 'pgw', 
        'pgx', 'pgy', 'pgz', 'phc', 'phd', 'phf', 'phj', 'phk', 'phq', 'phv', 'phx', 'piy', 
        'pjb', 'pjc', 'pjd', 'pjf', 'pjg', 'pjh', 'pji', 'pjj', 'pjk', 'pjl', 'pjm', 'pjn', 
        'pjp', 'pjq', 'pjr', 'pjs', 'pjt', 'pju', 'pjv', 'pjw', 'pjx', 'pjy', 'pjz', 'pkb', 
        'pkc', 'pkd', 'pkf', 'pkh', 'pkj', 'pkk', 'pkl', 'pkm', 'pko', 'pkp', 'pkq', 'pkr', 
        'pku', 'pkv', 'pkx', 'pky', 'pkz', 'plc', 'pld', 'plg', 'plh', 'plj', 'plk', 'pll', 
        'plm', 'pln', 'plq', 'plr', 'pls', 'plv', 'plw', 'plx', 'plz', 'pmb', 'pmc', 'pmd', 
        'pmf', 'pmg', 'pmh', 'pmj', 'pml', 'pmm', 'pmn', 'pmp', 'pmq', 'pmr', 'pmv', 'pmw', 
        'pmx', 'pmy', 'pmz', 'pnb', 'pnd', 'pnf', 'png', 'pnh', 'pnj', 'pnk', 'pnl', 'pnm', 
        'pnn', 'pnp', 'pnq', 'pnr', 'pns', 'pnt', 'pnv', 'pnw', 'pnz', 'ppc', 'ppf', 'ppg', 
        'ppj', 'ppk', 'ppq', 'ppv', 'ppw', 'ppx', 'ppz', 'pqa', 'pqb', 'pqc', 'pqd', 'pqe', 
        'pqf', 'pqg', 'pqh', 'pqi', 'pqj', 'pqk', 'pql', 'pqm', 'pqn', 'pqo', 'pqp', 'pqq', 
        'pqr', 'pqs', 'pqt', 'pqv', 'pqw', 'pqx', 'pqy', 'pqz', 'prb', 'prc', 'prd', 'prg', 
        'prh', 'prj', 'prk', 'prm', 'prq', 'prr', 'prt', 'prv', 'prw', 'prx', 'prz', 'psd', 
        'psg', 'psj', 'psv', 'psx', 'psz', 'ptj', 'ptq', 'ptv', 'ptx', 'ptz', 'puo', 'puv', 
        'puw', 'pvb', 'pvc', 'pvd', 'pve', 'pvf', 'pvg', 'pvh', 'pvj', 'pvk', 'pvl', 'pvm', 
        'pvn', 'pvp', 'pvq', 'pvs', 'pvu', 'pvv', 'pvw', 'pvx', 'pvy', 'pvz', 'pwb', 'pwd', 
        'pwf', 'pwg', 'pwj', 'pwk', 'pwl', 'pwm', 'pwn', 'pwp', 'pwq', 'pws', 'pwu', 'pwv', 
        'pww', 'pwx', 'pwz', 'pxa', 'pxb', 'pxc', 'pxd', 'pxe', 'pxf', 'pxg', 'pxh', 'pxi', 
        'pxj', 'pxk', 'pxl', 'pxm', 'pxn', 'pxo', 'pxp', 'pxq', 'pxr', 'pxs', 'pxt', 'pxu', 
        'pxv', 'pxw', 'pxx', 'pxy', 'pxz', 'pyq', 'pyy', 'pyz', 'pza', 'pzb', 'pzc', 'pzd', 
        'pze', 'pzf', 'pzg', 'pzh', 'pzj', 'pzk', 'pzl', 'pzm', 'pzn', 'pzo', 'pzp', 'pzq', 
        'pzr', 'pzs', 'pzt', 'pzu', 'pzv', 'pzw', 'pzx', 'pzy', 'pzz', 'qaa', 'qac', 'qae', 
        'qag', 'qah', 'qaj', 'qak', 'qal', 'qao', 'qap', 'qaq', 'qar', 'qau', 'qav', 'qaw', 
        'qax', 'qay', 'qaz', 'qba', 'qbb', 'qbc', 'qbd', 'qbe', 'qbf', 'qbg', 'qbh', 'qbi', 
        'qbj', 'qbk', 'qbl', 'qbm', 'qbn', 'qbo', 'qbp', 'qbq', 'qbr', 'qbs', 'qbt', 'qbu', 
        'qbv', 'qbw', 'qbx', 'qby', 'qbz', 'qca', 'qcb', 'qcc', 'qcd', 'qce', 'qcf', 'qcg', 
        'qch', 'qci', 'qcj', 'qck', 'qcl', 'qcm', 'qcn', 'qco', 'qcp', 'qcq', 'qcr', 'qcs', 
        'qct', 'qcu', 'qcv', 'qcw', 'qcx', 'qcy', 'qcz', 'qda', 'qdb', 'qdc', 'qdd', 'qde', 
        'qdf', 'qdg', 'qdh', 'qdi', 'qdj', 'qdk', 'qdl', 'qdm', 'qdn', 'qdo', 'qdp', 'qdq', 
        'qdr', 'qds', 'qdt', 'qdu', 'qdv', 'qdw', 'qdx', 'qdy', 'qdz', 'qea', 'qeb', 'qec', 
        'qee', 'qef', 'qeg', 'qeh', 'qei', 'qej', 'qek', 'qel', 'qem', 'qeo', 'qep', 'qeq', 
        'qes', 'qet', 'qeu', 'qev', 'qew', 'qex', 'qey', 'qez', 'qfa', 'qfb', 'qfd', 'qfe', 
        'qff', 'qfg', 'qfh', 'qfi', 'qfj', 'qfk', 'qfl', 'qfm', 'qfn', 'qfo', 'qfp', 'qfq', 
        'qfr', 'qfs', 'qft', 'qfu', 'qfv', 'qfw', 'qfx', 'qfy', 'qfz', 'qga', 'qgb', 'qgc', 
        'qgd', 'qge', 'qgf', 'qgg', 'qgh', 'qgi', 'qgj', 'qgk', 'qgl', 'qgm', 'qgn', 'qgo', 
        'qgp', 'qgq', 'qgr', 'qgs', 'qgt', 'qgu', 'qgv', 'qgw', 'qgx', 'qgz', 'qha', 'qhb', 
        'qhc', 'qhd', 'qhe', 'qhf', 'qhg', 'qhh', 'qhi', 'qhj', 'qhk', 'qhl', 'qhm', 'qhn', 
        'qho', 'qhp', 'qhq', 'qhr', 'qhs', 'qht', 'qhu', 'qhv', 'qhw', 'qhx', 'qhy', 'qhz', 
        'qic', 'qie', 'qif', 'qig', 'qih', 'qii', 'qij', 'qik', 'qim', 'qio', 'qip', 'qiq', 
        'qit', 'qiu', 'qiw', 'qix', 'qiz', 'qja', 'qjb', 'qjc', 'qjd', 'qje', 'qjf', 'qjg', 
        'qjh', 'qji', 'qjj', 'qjk', 'qjl', 'qjm', 'qjn', 'qjo', 'qjp', 'qjq', 'qjr', 'qjs', 
        'qjt', 'qju', 'qjv', 'qjw', 'qjx', 'qjy', 'qjz', 'qka', 'qkb', 'qkc', 'qkd', 'qke', 
        'qkf', 'qkg', 'qkh', 'qki', 'qkj', 'qkk', 'qkl', 'qkm', 'qkn', 'qko', 'qkp', 'qkq', 
        'qkr', 'qks', 'qkt', 'qku', 'qkv', 'qkw', 'qkx', 'qky', 'qkz', 'qla', 'qlb', 'qlc', 
        'qld', 'qle', 'qlf', 'qlg', 'qlh', 'qlj', 'qlk', 'qll', 'qlm', 'qln', 'qlo', 'qlp', 
        'qlq', 'qlr', 'qls', 'qlt', 'qlu', 'qlv', 'qlw', 'qlx', 'qly', 'qlz', 'qma', 'qmb', 
        'qmc', 'qmd', 'qme', 'qmf', 'qmg', 'qmh', 'qmi', 'qmj', 'qmk', 'qml', 'qmm', 'qmn', 
        'qmo', 'qmp', 'qmq', 'qmr', 'qms', 'qmt', 'qmu', 'qmv', 'qmw', 'qmx', 'qmy', 'qmz', 
        'qna', 'qnb', 'qnc', 'qnd', 'qne', 'qnf', 'qng', 'qnh', 'qni', 'qnj', 'qnk', 'qnl', 
        'qnm', 'qnn', 'qno', 'qnp', 'qnq', 'qnr', 'qns', 'qnt', 'qnu', 'qnv', 'qnw', 'qnx', 
        'qny', 'qnz', 'qoa', 'qob', 'qoc', 'qod', 'qoe', 'qof', 'qog', 'qoi', 'qoj', 'qok', 
        'qol', 'qom', 'qoo', 'qoq', 'qor', 'qos', 'qot', 'qou', 'qov', 'qow', 'qox', 'qoy', 
        'qoz', 'qpa', 'qpb', 'qpc', 'qpd', 'qpe', 'qpf', 'qpg', 'qph', 'qpi', 'qpj', 'qpk', 
        'qpl', 'qpm', 'qpn', 'qpo', 'qpp', 'qpq', 'qpr', 'qps', 'qpu', 'qpv', 'qpw', 'qpx', 
        'qpy', 'qpz', 'qqa', 'qqb', 'qqc', 'qqd', 'qqe', 'qqf', 'qqg', 'qqh', 'qqi', 'qqj', 
        'qqk', 'qql', 'qqm', 'qqn', 'qqo', 'qqp', 'qqq', 'qqr', 'qqs', 'qqt', 'qqw', 'qqx', 
        'qqy', 'qqz', 'qrb', 'qrd', 'qre', 'qrf', 'qrg', 'qrh', 'qri', 'qrj', 'qrk', 'qrl', 
        'qrm', 'qrn', 'qro', 'qrp', 'qrq', 'qrr', 'qru', 'qrv', 'qrw', 'qrx', 'qry', 'qrz', 
        'qsa', 'qsb', 'qsc', 'qsd', 'qse', 'qsf', 'qsg', 'qsi', 'qsj', 'qsk', 'qsl', 'qsm', 
        'qsn', 'qso', 'qsp', 'qsq', 'qsr', 'qss', 'qst', 'qsu', 'qsv', 'qsw', 'qsx', 'qsy', 
        'qsz', 'qtb', 'qtc', 'qte', 'qtf', 'qtg', 'qth', 'qtj', 'qtk', 'qtl', 'qtm', 'qtn', 
        'qtp', 'qtq', 'qtt', 'qtu', 'qtv', 'qtw', 'qtx', 'qtz', 'quc', 'quf', 'qug', 'quj', 
        'quk', 'qul', 'qup', 'qut', 'quw', 'qux', 'quz', 'qva', 'qvb', 'qvc', 'qvd', 'qve', 
        'qvf', 'qvg', 'qvh', 'qvi', 'qvj', 'qvk', 'qvl', 'qvm', 'qvn', 'qvo', 'qvp', 'qvq', 
        'qvr', 'qvs', 'qvt', 'qvu', 'qvv', 'qvw', 'qvx', 'qvy', 'qvz', 'qwa', 'qwb', 'qwc', 
        'qwd', 'qwf', 'qwg', 'qwh', 'qwi', 'qwj', 'qwk', 'qwm', 'qwn', 'qwo', 'qwp', 'qwq', 
        'qwr', 'qws', 'qwt', 'qwu', 'qwv', 'qww', 'qwx', 'qwy', 'qwz', 'qxa', 'qxb', 'qxc', 
        'qxd', 'qxe', 'qxf', 'qxg', 'qxh', 'qxi', 'qxj', 'qxk', 'qxl', 'qxm', 'qxn', 'qxo', 
        'qxp', 'qxq', 'qxr', 'qxs', 'qxt', 'qxu', 'qxv', 'qxw', 'qxx', 'qxy', 'qxz', 'qya', 
        'qyb', 'qyc', 'qyd', 'qye', 'qyf', 'qyg', 'qyh', 'qyi', 'qyj', 'qyk', 'qyl', 'qym', 
        'qyn', 'qyo', 'qyp', 'qyq', 'qyr', 'qys', 'qyt', 'qyu', 'qyv', 'qyw', 'qyx', 'qyy', 
        'qyz', 'qza', 'qzb', 'qzc', 'qzd', 'qze', 'qzf', 'qzg', 'qzh', 'qzi', 'qzj', 'qzk', 
        'qzl', 'qzm', 'qzn', 'qzo', 'qzp', 'qzq', 'qzr', 'qzs', 'qzt', 'qzu', 'qzv', 'qzw', 
        'qzx', 'qzy', 'qzz', 'rbc', 'rbf', 'rbg', 'rbj', 'rbp', 'rbq', 'rbv', 'rbx', 'rbz', 
        'rcj', 'rcm', 'rcq', 'rcw', 'rcx', 'rcz', 'rdj', 'rdq', 'rdx', 'rdz', 'rfj', 'rfk', 
        'rfq', 'rft', 'rfx', 'rgb', 'rgc', 'rgd', 'rgj', 'rgp', 'rgq', 'rgv', 'rgx', 'rgz', 
        'rhc', 'rhf', 'rhg', 'rhh', 'rhj', 'rhk', 'rhl', 'rhn', 'rhp', 'rhq', 'rhr', 'rht', 
        'rhv', 'rhx', 'rhz', 'rjb', 'rjc', 'rjd', 'rjf', 'rjg', 'rjh', 'rjj', 'rjk', 'rjl', 
        'rjm', 'rjn', 'rjp', 'rjq', 'rjr', 'rjs', 'rjt', 'rjv', 'rjw', 'rjx', 'rjy', 'rjz', 
        'rkj', 'rkq', 'rkv', 'rkx', 'rkz', 'rlj', 'rln', 'rlq', 'rlr', 'rlv', 'rlx', 'rlz', 
        'rmd', 'rmj', 'rmq', 'rmv', 'rmx', 'rmz', 'rnj', 'rnq', 'rnx', 'rnz', 'rpc', 'rpd', 
        'rpf', 'rpg', 'rpj', 'rpk', 'rpq', 'rpv', 'rpx', 'rpz', 'rqa', 'rqb', 'rqc', 'rqd', 
        'rqe', 'rqf', 'rqg', 'rqh', 'rqi', 'rqj', 'rqk', 'rql', 'rqm', 'rqn', 'rqo', 'rqp', 
        'rqq', 'rqr', 'rqs', 'rqt', 'rqv', 'rqw', 'rqx', 'rqy', 'rqz', 'rrc', 'rrd', 'rrj', 
        'rrp', 'rrq', 'rrv', 'rrx', 'rrz', 'rsg', 'rsj', 'rsr', 'rsx', 'rsz', 'rtk', 'rtx', 
        'rvb', 'rvc', 'rvd', 'rvf', 'rvg', 'rvh', 'rvj', 'rvm', 'rvn', 'rvp', 'rvq', 'rvr', 
        'rvt', 'rvv', 'rvw', 'rvx', 'rvz', 'rwb', 'rwc', 'rwf', 'rwg', 'rwj', 'rwk', 'rwl', 
        'rwm', 'rwn', 'rwp', 'rwq', 'rws', 'rwv', 'rwx', 'rwz', 'rxa', 'rxb', 'rxc', 'rxd', 
        'rxe', 'rxf', 'rxg', 'rxh', 'rxj', 'rxk', 'rxl', 'rxm', 'rxn', 'rxo', 'rxp', 'rxq', 
        'rxr', 'rxs', 'rxt', 'rxu', 'rxv', 'rxw', 'rxx', 'rxz', 'ryj', 'ryq', 'ryy', 'rzc', 
        'rzd', 'rzf', 'rzg', 'rzh', 'rzj', 'rzk', 'rzl', 'rzm', 'rzp', 'rzq', 'rzs', 'rzt', 
        'rzv', 'rzw', 'rzx', 'rzz', 'sbc', 'sbd', 'sbf', 'sbg', 'sbh', 'sbj', 'sbk', 'sbm', 
        'sbn', 'sbp', 'sbq', 'sbs', 'sbt', 'sbv', 'sbw', 'sbx', 'sbz', 'scb', 'scd', 'scg', 
        'scj', 'sck', 'scp', 'scq', 'scv', 'scw', 'scx', 'scz', 'sdb', 'sdc', 'sdd', 'sdf', 
        'sdg', 'sdh', 'sdj', 'sdk', 'sdm', 'sdp', 'sdq', 'sdt', 'sdv', 'sdw', 'sdx', 'sdz', 
        'sfb', 'sfc', 'sff', 'sfg', 'sfh', 'sfj', 'sfk', 'sfn', 'sfp', 'sfq', 'sfs', 'sft', 
        'sfv', 'sfw', 'sfx', 'sgb', 'sgc', 'sgf', 'sgg', 'sgj', 'sgk', 'sgp', 'sgq', 'sgs', 
        'sgt', 'sgv', 'sgw', 'sgx', 'sgz', 'shx', 'shz', 'sjb', 'sjc', 'sjd', 'sjf', 'sjg', 
        'sjh', 'sjj', 'sjk', 'sjl', 'sjm', 'sjn', 'sjp', 'sjq', 'sjr', 'sjs', 'sjt', 'sjv', 
        'sjw', 'sjx', 'sjy', 'sjz', 'skc', 'skd', 'skk', 'skq', 'skv', 'skx', 'skz', 'slb', 
        'slc', 'slg', 'slh', 'slj', 'slk', 'slm', 'sln', 'slp', 'slq', 'slr', 'slv', 'slw', 
        'slx', 'slz', 'smb', 'smc', 'smf', 'smg', 'smj', 'smk', 'smq', 'smt', 'smv', 'smw', 
        'smx', 'smz', 'snb', 'snc', 'snd', 'snf', 'sng', 'snh', 'snj', 'snk', 'snl', 'snm', 
        'snn', 'snp', 'snq', 'snr', 'snv', 'snw', 'snx', 'snz', 'spd', 'spj', 'spk', 'spm', 
        'spq', 'spv', 'spw', 'spx', 'spz', 'sqa', 'sqb', 'sqc', 'sqe', 'sqf', 'sqg', 'sqh', 
        'sqi', 'sqj', 'sqk', 'sql', 'sqm', 'sqn', 'sqo', 'sqp', 'sqs', 'sqt', 'sqv', 'sqw', 
        'sqx', 'sqy', 'sqz', 'srb', 'src', 'srd', 'srf', 'srg', 'srj', 'srk', 'srl', 'srm', 
        'srn', 'srp', 'srq', 'srr', 'srt', 'srv', 'srw', 'srx', 'srz', 'ssx', 'ssz', 'stq', 
        'svb', 'svd', 'svf', 'svh', 'svj', 'svk', 'svl', 'svm', 'svn', 'svq', 'svs', 'svt', 
        'svv', 'svw', 'svx', 'svy', 'svz', 'swb', 'swc', 'swd', 'swf', 'swg', 'swh', 'swj', 
        'swk', 'swm', 'swn', 'swp', 'swq', 'sws', 'swt', 'swv', 'sww', 'swx', 'swz', 'sxa', 
        'sxb', 'sxc', 'sxd', 'sxe', 'sxf', 'sxg', 'sxh', 'sxi', 'sxj', 'sxk', 'sxl', 'sxm', 
        'sxn', 'sxo', 'sxp', 'sxq', 'sxr', 'sxs', 'sxt', 'sxu', 'sxv', 'sxw', 'sxx', 'sxy', 
        'sxz', 'syj', 'syq', 'syx', 'syy', 'szb', 'szc', 'szd', 'szf', 'szg', 'szh', 'szj', 
        'szm', 'szn', 'szp', 'szq', 'szr', 'szs', 'szu', 'szv', 'szw', 'szx', 'szz', 'tbc', 
        'tbf', 'tbg', 'tbh', 'tbj', 'tbk', 'tbm', 'tbn', 'tbp', 'tbq', 'tbt', 'tbv', 'tbw', 
        'tbx', 'tbz', 'tcb', 'tcc', 'tcd', 'tcf', 'tcg', 'tcj', 'tcm', 'tcn', 'tcp', 'tcq', 
        'tcs', 'tct', 'tcv', 'tcw', 'tcx', 'tdb', 'tdc', 'tdf', 'tdg', 'tdh', 'tdj', 'tdk', 
        'tdl', 'tdm', 'tdn', 'tdp', 'tdq', 'tds', 'tdt', 'tdv', 'tdx', 'tdz', 'tfb', 'tfc', 
        'tfg', 'tfh', 'tfj', 'tfk', 'tfm', 'tfn', 'tfp', 'tfq', 'tfs', 'tft', 'tfv', 'tfw', 
        'tfx', 'tfy', 'tfz', 'tgb', 'tgc', 'tgd', 'tgf', 'tgg', 'tgh', 'tgj', 'tgk', 'tgm', 
        'tgp', 'tgq', 'tgs', 'tgv', 'tgw', 'tgx', 'tgy', 'tgz', 'thj', 'thx', 'thz', 'tjb', 
        'tjd', 'tjf', 'tjg', 'tjh', 'tjj', 'tjk', 'tjl', 'tjm', 'tjn', 'tjp', 'tjq', 'tjr', 
        'tjs', 'tjt', 'tjv', 'tjw', 'tjx', 'tjy', 'tjz', 'tkb', 'tkc', 'tkd', 'tkf', 'tkg', 
        'tkh', 'tkj', 'tkk', 'tkl', 'tkm', 'tkp', 'tkq', 'tkr', 'tkv', 'tkw', 'tkx', 'tky', 
        'tkz', 'tlb', 'tlc', 'tld', 'tlf', 'tlh', 'tlj', 'tlk', 'tlm', 'tlp', 'tlq', 'tlt', 
        'tlv', 'tlw', 'tlx', 'tlz', 'tmb', 'tmc', 'tmd', 'tmf', 'tmg', 'tmk', 'tml', 'tmn', 
        'tmp', 'tmq', 'tmr', 'tms', 'tmt', 'tmv', 'tmw', 'tmx', 'tmz', 'tnb', 'tnd', 'tnf', 
        'tnh', 'tnj', 'tnk', 'tnm', 'tnn', 'tnq', 'tns', 'tnv', 'tnw', 'tnx', 'tny', 'tnz', 
        'tpb', 'tpc', 'tpg', 'tpj', 'tpp', 'tpq', 'tpt', 'tpv', 'tpw', 'tpx', 'tpz', 'tqa', 
        'tqb', 'tqc', 'tqd', 'tqe', 'tqf', 'tqg', 'tqh', 'tqi', 'tqj', 'tqk', 'tql', 'tqm', 
        'tqn', 'tqo', 'tqp', 'tqq', 'tqr', 'tqs', 'tqt', 'tqv', 'tqw', 'tqx', 'tqy', 'tqz', 
        'trb', 'trg', 'trj', 'trk', 'trm', 'trq', 'trr', 'trv', 'trw', 'trx', 'trz', 'tsd', 
        'tsg', 'tsq', 'tsx', 'tsz', 'ttc', 'ttk', 'ttp', 'ttq', 'ttx', 'ttz', 'tuj', 'tvb', 
        'tvc', 'tvd', 'tvf', 'tvg', 'tvh', 'tvj', 'tvk', 'tvl', 'tvm', 'tvn', 'tvp', 'tvq', 
        'tvr', 'tvs', 'tvt', 'tvu', 'tvv', 'tvw', 'tvx', 'tvz', 'twb', 'twc', 'twd', 'twf', 
        'twg', 'twj', 'twk', 'twl', 'twm', 'twn', 'twq', 'tws', 'twt', 'twv', 'twx', 'twz', 
        'txa', 'txb', 'txc', 'txd', 'txe', 'txf', 'txg', 'txh', 'txj', 'txk', 'txl', 'txm', 
        'txn', 'txo', 'txp', 'txq', 'txr', 'txs', 'txu', 'txv', 'txw', 'txx', 'txz', 'tyj', 
        'tyv', 'tyy', 'tyz', 'tzd', 'tzg', 'tzh', 'tzj', 'tzq', 'tzt', 'tzw', 'tzx', 'tzz', 
        'ubx', 'ucf', 'ucj', 'ucm', 'ucq', 'ucv', 'ucw', 'ucx', 'ucz', 'udj', 'udk', 'udq', 
        'udv', 'udx', 'uek', 'ueq', 'ufc', 'ufd', 'ufh', 'ufj', 'ufm', 'ufn', 'ufp', 'ufq', 
        'ufv', 'ufw', 'ufx', 'ufz', 'ugc', 'ugj', 'ugq', 'ugv', 'ugx', 'uhb', 'uhc', 'uhd', 
        'uhf', 'uhg', 'uhh', 'uhj', 'uhk', 'uhm', 'uhp', 'uhq', 'uhv', 'uhx', 'uhz', 'uiw', 
        'uiy', 'ujb', 'ujc', 'ujf', 'ujg', 'ujh', 'ujj', 'ujk', 'ujl', 'ujm', 'ujn', 'ujp', 
        'ujq', 'ujs', 'ujv', 'ujw', 'ujx', 'ujz', 'ukf', 'ukg', 'ukj', 'ukm', 'ukn', 'ukq', 
        'ukv', 'ukw', 'ukx', 'ukz', 'ulj', 'umx', 'uoe', 'uof', 'uoj', 'uox', 'upx', 'upz', 
        'uqa', 'uqb', 'uqc', 'uqd', 'uqe', 'uqf', 'uqg', 'uqh', 'uqi', 'uqj', 'uqk', 'uql', 
        'uqm', 'uqn', 'uqo', 'uqp', 'uqq', 'uqr', 'uqt', 'uqv', 'uqw', 'uqx', 'uqy', 'uqz', 
        'urx', 'usx', 'utx', 'uue', 'uuf', 'uug', 'uuh', 'uui', 'uuj', 'uuk', 'uuo', 'uup', 
        'uuq', 'uuu', 'uuv', 'uuw', 'uux', 'uuy', 'uuz', 'uvb', 'uvc', 'uvd', 'uvf', 'uvg', 
        'uvh', 'uvj', 'uvk', 'uvm', 'uvn', 'uvp', 'uvq', 'uvs', 'uvt', 'uvw', 'uvx', 'uvz', 
        'uwc', 'uwd', 'uwf', 'uwg', 'uwh', 'uwj', 'uwk', 'uwm', 'uwn', 'uwp', 'uwq', 'uwr', 
        'uwt', 'uwu', 'uwv', 'uww', 'uwx', 'uwy', 'uwz', 'uxc', 'uxd', 'uxf', 'uxj', 'uxk', 
        'uxn', 'uxp', 'uxq', 'uxv', 'uxx', 'uxz', 'uyc', 'uyf', 'uyj', 'uym', 'uyp', 'uyq', 
        'uyr', 'uyv', 'uyx', 'uyy', 'uyz', 'uzd', 'uzf', 'uzg', 'uzk', 'uzn', 'uzp', 'uzq', 
        'uzr', 'uzs', 'uzt', 'uzx', 'vba', 'vbb', 'vbc', 'vbd', 'vbe', 'vbf', 'vbg', 'vbh', 
        'vbi', 'vbj', 'vbk', 'vbl', 'vbm', 'vbn', 'vbo', 'vbp', 'vbq', 'vbr', 'vbs', 'vbt', 
        'vbu', 'vbv', 'vbw', 'vbx', 'vby', 'vbz', 'vca', 'vcb', 'vcc', 'vcd', 'vcf', 'vcg', 
        'vcj', 'vck', 'vcl', 'vcm', 'vcn', 'vco', 'vcp', 'vcq', 'vcr', 'vcs', 'vct', 'vcu', 
        'vcv', 'vcw', 'vcx', 'vcy', 'vcz', 'vdb', 'vdc', 'vdd', 'vde', 'vdf', 'vdg', 'vdh', 
        'vdj', 'vdk', 'vdl', 'vdm', 'vdn', 'vdq', 'vdr', 'vds', 'vdt', 'vdu', 'vdv', 'vdw', 
        'vdx', 'vdy', 'vdz', 'vfa', 'vfb', 'vfc', 'vfd', 'vfe', 'vff', 'vfg', 'vfh', 'vfi', 
        'vfj', 'vfk', 'vfl', 'vfm', 'vfn', 'vfo', 'vfp', 'vfq', 'vfr', 'vfs', 'vft', 'vfu', 
        'vfv', 'vfw', 'vfx', 'vfy', 'vfz', 'vgb', 'vgc', 'vgd', 'vge', 'vgf', 'vgg', 'vgi', 
        'vgj', 'vgk', 'vgl', 'vgm', 'vgn', 'vgo', 'vgp', 'vgq', 'vgr', 'vgt', 'vgu', 'vgv', 
        'vgw', 'vgx', 'vgy', 'vgz', 'vha', 'vhb', 'vhc', 'vhd', 'vhe', 'vhf', 'vhg', 'vhh', 
        'vhi', 'vhj', 'vhk', 'vhl', 'vhm', 'vhn', 'vho', 'vhp', 'vhq', 'vhr', 'vhs', 'vht', 
        'vhu', 'vhv', 'vhw', 'vhx', 'vhy', 'vhz', 'viw', 'vja', 'vjb', 'vjc', 'vjd', 'vje', 
        'vjf', 'vjg', 'vjh', 'vji', 'vjj', 'vjk', 'vjl', 'vjm', 'vjn', 'vjo', 'vjp', 'vjq', 
        'vjr', 'vjs', 'vjt', 'vju', 'vjv', 'vjw', 'vjx', 'vjy', 'vjz', 'vka', 'vkb', 'vkc', 
        'vkd', 'vke', 'vkf', 'vkg', 'vki', 'vkj', 'vkk', 'vkl', 'vkm', 'vkn', 'vko', 'vkp', 
        'vkq', 'vkr', 'vks', 'vku', 'vkv', 'vkw', 'vkx', 'vky', 'vkz', 'vlb', 'vlc', 'vlf', 
        'vlg', 'vlh', 'vlj', 'vlk', 'vlm', 'vln', 'vlp', 'vlq', 'vlr', 'vlu', 'vlv', 'vlw', 
        'vlx', 'vlz', 'vmb', 'vmc', 'vmd', 'vme', 'vmf', 'vmg', 'vmh', 'vmj', 'vmk', 'vml', 
        'vmm', 'vmn', 'vmo', 'vmp', 'vmq', 'vmr', 'vmt', 'vmu', 'vmv', 'vmw', 'vmx', 'vmy', 
        'vmz', 'vnb', 'vnc', 'vnd', 'vne', 'vnf', 'vng', 'vnh', 'vnj', 'vnk', 'vnl', 'vnm', 
        'vnn', 'vno', 'vnp', 'vnq', 'vnr', 'vns', 'vnt', 'vnu', 'vnv', 'vnw', 'vnx', 'vny', 
        'vnz', 'voh', 'voj', 'vpa', 'vpb', 'vpc', 'vpd', 'vpe', 'vpf', 'vpg', 'vph', 'vpi', 
        'vpj', 'vpk', 'vpl', 'vpm', 'vpn', 'vpo', 'vpp', 'vpq', 'vps', 'vpt', 'vpu', 'vpv', 
        'vpw', 'vpx', 'vpy', 'vpz', 'vqa', 'vqb', 'vqc', 'vqd', 'vqe', 'vqf', 'vqg', 'vqh', 
        'vqi', 'vqj', 'vqk', 'vql', 'vqm', 'vqn', 'vqo', 'vqp', 'vqq', 'vqr', 'vqs', 'vqt', 
        'vqu', 'vqv', 'vqw', 'vqx', 'vqy', 'vqz', 'vrc', 'vrd', 'vrf', 'vrg', 'vrh', 'vrj', 
        'vrk', 'vrl', 'vrm', 'vrn', 'vrp', 'vrq', 'vrr', 'vrs', 'vrt', 'vru', 'vrv', 'vrw', 
        'vrx', 'vrz', 'vsa', 'vsc', 'vsd', 'vse', 'vsf', 'vsg', 'vsi', 'vsj', 'vsl', 'vsm', 
        'vsn', 'vso', 'vsp', 'vsq', 'vsr', 'vst', 'vsu', 'vsv', 'vsw', 'vsx', 'vsy', 'vsz', 
        'vtb', 'vtc', 'vtd', 'vte', 'vtf', 'vtg', 'vth', 'vti', 'vtj', 'vtk', 'vtl', 'vtm', 
        'vtn', 'vto', 'vtp', 'vtq', 'vtr', 'vtt', 'vtu', 'vtv', 'vtw', 'vtx', 'vty', 'vtz', 
        'vua', 'vub', 'vuf', 'vuh', 'vuj', 'vuk', 'vuo', 'vup', 'vuq', 'vuu', 'vuw', 'vux', 
        'vuy', 'vuz', 'vvb', 'vvc', 'vvd', 'vvf', 'vvg', 'vvh', 'vvj', 'vvk', 'vvm', 'vvn', 
        'vvo', 'vvp', 'vvq', 'vvr', 'vvs', 'vvt', 'vvu', 'vvv', 'vvw', 'vvx', 'vvz', 'vwa', 
        'vwb', 'vwc', 'vwd', 'vwe', 'vwf', 'vwg', 'vwh', 'vwi', 'vwj', 'vwk', 'vwl', 'vwm', 
        'vwn', 'vwo', 'vwp', 'vwq', 'vwr', 'vwt', 'vwu', 'vwv', 'vww', 'vwx', 'vwy', 'vwz', 
        'vxa', 'vxb', 'vxc', 'vxd', 'vxe', 'vxf', 'vxg', 'vxh', 'vxi', 'vxj', 'vxk', 'vxl', 
        'vxm', 'vxn', 'vxo', 'vxp', 'vxq', 'vxr', 'vxs', 'vxt', 'vxu', 'vxv', 'vxw', 'vxx', 
        'vxy', 'vxz', 'vyc', 'vyd', 'vyg', 'vyj', 'vyk', 'vym', 'vyo', 'vyp', 'vyq', 'vyt', 
        'vyv', 'vyx', 'vyz', 'vza', 'vzb', 'vzc', 'vzd', 'vze', 'vzf', 'vzg', 'vzh', 'vzi', 
        'vzj', 'vzk', 'vzl', 'vzm', 'vzn', 'vzp', 'vzq', 'vzr', 'vzs', 'vzt', 'vzv', 'vzw', 
        'vzx', 'vzy', 'vzz', 'wao', 'waq', 'wbb', 'wbc', 'wbd', 'wbf', 'wbg', 'wbh', 'wbj', 
        'wbk', 'wbm', 'wbn', 'wbp', 'wbq', 'wbs', 'wbt', 'wbv', 'wbx', 'wbz', 'wcb', 'wcc', 
        'wcd', 'wcf', 'wcg', 'wcj', 'wck', 'wcm', 'wcn', 'wcp', 'wcq', 'wcs', 'wct', 'wcv', 
        'wcw', 'wcx', 'wcy', 'wcz', 'wdb', 'wdc', 'wdd', 'wdf', 'wdg', 'wdh', 'wdj', 'wdk', 
        'wdm', 'wdp', 'wdq', 'wdt', 'wdv', 'wdx', 'wdz', 'weq', 'weu', 'wex', 'wfb', 'wfc', 
        'wfd', 'wfg', 'wfh', 'wfj', 'wfk', 'wfm', 'wfn', 'wfp', 'wfq', 'wft', 'wfv', 'wfw', 
        'wfx', 'wfy', 'wfz', 'wgb', 'wgc', 'wgd', 'wgf', 'wgg', 'wgj', 'wgk', 'wgm', 'wgn', 
        'wgp', 'wgq', 'wgs', 'wgt', 'wgv', 'wgw', 'wgx', 'wgy', 'wgz', 'whb', 'whc', 'whd', 
        'whg', 'whh', 'whj', 'whk', 'whl', 'whm', 'whn', 'whp', 'whq', 'wht', 'whv', 'whw', 
        'whx', 'whz', 'wih', 'wij', 'wio', 'wiq', 'wiu', 'wja', 'wjb', 'wjd', 'wje', 'wjf', 
        'wjg', 'wjh', 'wji', 'wjj', 'wjk', 'wjl', 'wjm', 'wjn', 'wjp', 'wjq', 'wjr', 'wjs', 
        'wjt', 'wjv', 'wjw', 'wjx', 'wjy', 'wjz', 'wkc', 'wkd', 'wkf', 'wkg', 'wkj', 'wkk', 
        'wko', 'wkp', 'wkq', 'wkt', 'wku', 'wkv', 'wkx', 'wkz', 'wlc', 'wlj', 'wlk', 'wlq', 
        'wlv', 'wlx', 'wlz', 'wmc', 'wmd', 'wmf', 'wmg', 'wmh', 'wmj', 'wml', 'wmn', 'wmp', 
        'wmq', 'wmr', 'wmt', 'wmu', 'wmv', 'wmw', 'wmx', 'wmy', 'wmz', 'wnj', 'wnk', 'wnq', 
        'wnv', 'wnx', 'wnz', 'woj', 'woq', 'wox', 'woz', 'wpb', 'wpc', 'wpd', 'wpf', 'wpg', 
        'wpj', 'wpk', 'wpn', 'wpp', 'wpq', 'wpt', 'wpv', 'wpw', 'wpx', 'wpz', 'wqa', 'wqb', 
        'wqc', 'wqd', 'wqe', 'wqf', 'wqg', 'wqh', 'wqi', 'wqj', 'wqk', 'wql', 'wqm', 'wqn', 
        'wqo', 'wqp', 'wqq', 'wqr', 'wqs', 'wqt', 'wqv', 'wqw', 'wqx', 'wqy', 'wqz', 'wrb', 
        'wrc', 'wrf', 'wrg', 'wrh', 'wrj', 'wrk', 'wrl', 'wrm', 'wrp', 'wrq', 'wrr', 'wrs', 
        'wrt', 'wrv', 'wrw', 'wrx', 'wrz', 'wsj', 'wsq', 'wsx', 'wsz', 'wtb', 'wtd', 'wtf', 
        'wtg', 'wtj', 'wtk', 'wtl', 'wtm', 'wtn', 'wtp', 'wtq', 'wtt', 'wtv', 'wtx', 'wtz', 
        'wua', 'wub', 'wue', 'wuh', 'wui', 'wuj', 'wuk', 'wuo', 'wuq', 'wuu', 'wuv', 'wuw', 
        'wux', 'wuy', 'wva', 'wvb', 'wvc', 'wvd', 'wvf', 'wvg', 'wvh', 'wvj', 'wvk', 'wvl', 
        'wvm', 'wvn', 'wvo', 'wvp', 'wvq', 'wvr', 'wvs', 'wvt', 'wvu', 'wvv', 'wvw', 'wvx', 
        'wvy', 'wvz', 'wwb', 'wwc', 'wwd', 'wwf', 'wwg', 'wwj', 'wwk', 'wwl', 'wwm', 'wwn', 
        'wwp', 'wwq', 'wws', 'wwt', 'wwu', 'wwv', 'www', 'wwx', 'wwy', 'wwz', 'wxa', 'wxb', 
        'wxc', 'wxd', 'wxe', 'wxf', 'wxg', 'wxh', 'wxi', 'wxj', 'wxk', 'wxl', 'wxm', 'wxn', 
        'wxo', 'wxp', 'wxq', 'wxr', 'wxs', 'wxt', 'wxu', 'wxv', 'wxw', 'wxx', 'wxy', 'wxz', 
        'wyf', 'wyg', 'wyi', 'wyj', 'wyq', 'wyu', 'wyw', 'wyx', 'wyy', 'wyz', 'wza', 'wzb', 
        'wzc', 'wzd', 'wzf', 'wzg', 'wzh', 'wzj', 'wzk', 'wzm', 'wzn', 'wzo', 'wzp', 'wzq', 
        'wzr', 'wzs', 'wzt', 'wzu', 'wzv', 'wzw', 'wzx', 'wzz', 'xaa', 'xaj', 'xao', 'xaq', 
        'xaw', 'xay', 'xbb', 'xbc', 'xbd', 'xbf', 'xbg', 'xbh', 'xbj', 'xbk', 'xbm', 'xbn', 
        'xbp', 'xbq', 'xbs', 'xbt', 'xbv', 'xbw', 'xbx', 'xbz', 'xcb', 'xcc', 'xcd', 'xcf', 
        'xcg', 'xcj', 'xck', 'xcm', 'xcn', 'xcp', 'xcq', 'xcs', 'xcv', 'xcw', 'xcx', 'xcz', 
        'xdb', 'xdc', 'xdd', 'xdf', 'xdg', 'xdh', 'xdj', 'xdk', 'xdl', 'xdm', 'xdn', 'xdo', 
        'xdp', 'xdq', 'xds', 'xdt', 'xdu', 'xdv', 'xdw', 'xdx', 'xdy', 'xdz', 'xef', 'xeh', 
        'xei', 'xej', 'xek', 'xep', 'xev', 'xew', 'xex', 'xez', 'xfb', 'xfc', 'xfd', 'xff', 
        'xfg', 'xfh', 'xfj', 'xfk', 'xfm', 'xfn', 'xfp', 'xfq', 'xfr', 'xfs', 'xft', 'xfv', 
        'xfw', 'xfx', 'xfy', 'xfz', 'xgb', 'xgc', 'xgd', 'xge', 'xgf', 'xgg', 'xgh', 'xgj', 
        'xgk', 'xgm', 'xgn', 'xgp', 'xgq', 'xgs', 'xgt', 'xgv', 'xgw', 'xgx', 'xgy', 'xgz', 
        'xhc', 'xhd', 'xhf', 'xhg', 'xhh', 'xhj', 'xhk', 'xhm', 'xhn', 'xhp', 'xhq', 'xhr', 
        'xhs', 'xht', 'xhv', 'xhw', 'xhx', 'xhz', 'xij', 'xik', 'xiq', 'xiy', 'xiz', 'xja', 
        'xjb', 'xjc', 'xjd', 'xje', 'xjf', 'xjg', 'xjh', 'xji', 'xjj', 'xjk', 'xjl', 'xjm', 
        'xjn', 'xjo', 'xjp', 'xjq', 'xjr', 'xjs', 'xjt', 'xju', 'xjv', 'xjw', 'xjx', 'xjy', 
        'xjz', 'xka', 'xkb', 'xkc', 'xkd', 'xkf', 'xkg', 'xkh', 'xkj', 'xkk', 'xkl', 'xkm', 
        'xkn', 'xko', 'xkp', 'xkq', 'xkr', 'xks', 'xkt', 'xku', 'xkv', 'xkw', 'xkx', 'xky', 
        'xkz', 'xlb', 'xlc', 'xld', 'xlf', 'xlg', 'xlh', 'xlj', 'xlk', 'xll', 'xlm', 'xln', 
        'xlp', 'xlq', 'xlr', 'xlt', 'xlu', 'xlv', 'xlw', 'xlx', 'xlz', 'xmb', 'xmc', 'xmd', 
        'xmf', 'xmg', 'xmh', 'xmj', 'xmk', 'xml', 'xmm', 'xmn', 'xmp', 'xmq', 'xmr', 'xms', 
        'xmt', 'xmu', 'xmv', 'xmw', 'xmx', 'xmy', 'xmz', 'xna', 'xnb', 'xnc', 'xnd', 'xnf', 
        'xng', 'xnh', 'xni', 'xnj', 'xnk', 'xnl', 'xnm', 'xnn', 'xno', 'xnp', 'xnq', 'xnr', 
        'xns', 'xnt', 'xnu', 'xnv', 'xnw', 'xnx', 'xny', 'xnz', 'xoj', 'xoo', 'xoq', 'xow', 
        'xox', 'xpb', 'xpc', 'xpf', 'xpg', 'xpj', 'xpk', 'xpm', 'xpn', 'xpp', 'xpq', 'xps', 
        'xpv', 'xpx', 'xpz', 'xqa', 'xqb', 'xqc', 'xqd', 'xqe', 'xqf', 'xqg', 'xqh', 'xqi', 
        'xqj', 'xqk', 'xql', 'xqm', 'xqn', 'xqo', 'xqp', 'xqq', 'xqr', 'xqs', 'xqt', 'xqv', 
        'xqw', 'xqx', 'xqy', 'xqz', 'xrb', 'xrc', 'xrd', 'xrf', 'xrg', 'xrh', 'xrj', 'xrk', 
        'xrl', 'xrm', 'xrn', 'xrp', 'xrq', 'xrr', 'xrs', 'xrt', 'xrv', 'xrw', 'xry', 'xrz', 
        'xsb', 'xsd', 'xsf', 'xsg', 'xsj', 'xsl', 'xsm', 'xsn', 'xsq', 'xsr', 'xss', 'xsv', 
        'xsx', 'xsy', 'xsz', 'xtc', 'xtf', 'xtj', 'xtk', 'xtp', 'xtq', 'xtt', 'xtv', 'xtw', 
        'xtx', 'xtz', 'xue', 'xuf', 'xug', 'xuh', 'xui', 'xuj', 'xuk', 'xuq', 'xut', 'xuu', 
        'xuw', 'xux', 'xuy', 'xuz', 'xva', 'xvb', 'xvc', 'xvd', 'xve', 'xvf', 'xvg', 'xvh', 
        'xvj', 'xvk', 'xvl', 'xvm', 'xvn', 'xvo', 'xvp', 'xvq', 'xvr', 'xvs', 'xvt', 'xvu', 
        'xvv', 'xvw', 'xvx', 'xvy', 'xvz', 'xwb', 'xwc', 'xwd', 'xwf', 'xwg', 'xwh', 'xwj', 
        'xwk', 'xwl', 'xwm', 'xwn', 'xwp', 'xwq', 'xwr', 'xws', 'xwt', 'xwu', 'xwv', 'xww', 
        'xwx', 'xwy', 'xwz', 'xxa', 'xxb', 'xxc', 'xxd', 'xxe', 'xxf', 'xxg', 'xxh', 'xxj', 
        'xxk', 'xxl', 'xxm', 'xxn', 'xxp', 'xxq', 'xxr', 'xxs', 'xxt', 'xxu', 'xxw', 'xxy', 
        'xxz', 'xyj', 'xyv', 'xyx', 'xyy', 'xza', 'xzb', 'xzc', 'xzd', 'xze', 'xzf', 'xzg', 
        'xzh', 'xzi', 'xzj', 'xzk', 'xzl', 'xzm', 'xzn', 'xzp', 'xzq', 'xzr', 'xzs', 'xzt', 
        'xzu', 'xzv', 'xzw', 'xzx', 'xzy', 'xzz', 'ybc', 'ybf', 'ybg', 'ybh', 'ybj', 'ybk', 
        'ybm', 'ybn', 'ybp', 'ybq', 'ybs', 'ybt', 'ybv', 'ybw', 'ybx', 'ybz', 'ycb', 'ycc', 
        'ycd', 'ycf', 'ycg', 'ycj', 'ycm', 'ycp', 'ycq', 'ycs', 'ycv', 'ycw', 'ycx', 'ycz', 
        'ydb', 'ydc', 'ydf', 'ydg', 'ydh', 'ydj', 'ydk', 'ydm', 'ydp', 'ydq', 'ydt', 'ydv', 
        'ydw', 'ydx', 'ydz', 'yej', 'yek', 'yeq', 'yfb', 'yfc', 'yfd', 'yff', 'yfg', 'yfh', 
        'yfj', 'yfm', 'yfn', 'yfp', 'yfq', 'yfs', 'yfv', 'yfw', 'yfx', 'ygb', 'ygc', 'ygf', 
        'ygj', 'ygk', 'ygp', 'ygq', 'ygs', 'ygt', 'ygv', 'ygw', 'ygx', 'ygz', 'yhb', 'yhc', 
        'yhd', 'yhf', 'yhg', 'yhh', 'yhj', 'yhk', 'yhl', 'yhp', 'yhq', 'yhr', 'yhs', 'yhv', 
        'yhx', 'yhz', 'yih', 'yij', 'yiq', 'yiu', 'yiv', 'yiw', 'yix', 'yiy', 'yjb', 'yjc', 
        'yjd', 'yje', 'yjf', 'yjg', 'yjh', 'yji', 'yjj', 'yjk', 'yjl', 'yjm', 'yjn', 'yjo', 
        'yjp', 'yjq', 'yjr', 'yjs', 'yjt', 'yju', 'yjv', 'yjw', 'yjx', 'yjy', 'yjz', 'ykb', 
        'ykc', 'ykd', 'ykf', 'ykg', 'ykk', 'ykm', 'ykp', 'ykq', 'ykr', 'ykv', 'ykw', 'ykx', 
        'yky', 'ykz', 'ylj', 'ylw', 'ylx', 'ylz', 'ymd', 'ymf', 'ymg', 'ymj', 'ymq', 'ymv', 
        'ymw', 'ymx', 'ymz', 'ynj', 'ynm', 'ynq', 'ynv', 'ypb', 'ypc', 'ypd', 'ypf', 'ypg', 
        'ypj', 'ypk', 'ypm', 'ypq', 'ypv', 'ypx', 'ypz', 'yqa', 'yqb', 'yqc', 'yqd', 'yqe', 
        'yqf', 'yqg', 'yqh', 'yqi', 'yqj', 'yqk', 'yql', 'yqm', 'yqn', 'yqo', 'yqp', 'yqq', 
        'yqr', 'yqs', 'yqt', 'yqv', 'yqw', 'yqx', 'yqy', 'yqz', 'yrj', 'yrk', 'yrq', 'yrv', 
        'yrw', 'yrx', 'yrz', 'ysd', 'ysj', 'ysq', 'ysv', 'ysx', 'ytb', 'ytc', 'ytd', 'ytf', 
        'ytg', 'ytj', 'ytk', 'ytn', 'ytp', 'ytq', 'ytv', 'ytx', 'ytz', 'yuj', 'yuo', 'yuu', 
        'yuw', 'yux', 'yvb', 'yvc', 'yvd', 'yvf', 'yvg', 'yvh', 'yvj', 'yvk', 'yvl', 'yvm', 
        'yvn', 'yvp', 'yvq', 'yvr', 'yvs', 'yvt', 'yvv', 'yvw', 'yvx', 'yvy', 'yvz', 'ywb', 
        'ywf', 'ywg', 'ywj', 'ywk', 'ywl', 'ywm', 'ywn', 'ywp', 'ywq', 'yws', 'ywt', 'ywu', 
        'ywv', 'yww', 'ywx', 'ywz', 'yxb', 'yxc', 'yxd', 'yxf', 'yxg', 'yxh', 'yxj', 'yxk', 
        'yxl', 'yxm', 'yxn', 'yxp', 'yxq', 'yxr', 'yxs', 'yxt', 'yxu', 'yxv', 'yxw', 'yxx', 
        'yxz', 'yyb', 'yyc', 'yyd', 'yyf', 'yyg', 'yyh', 'yyj', 'yyk', 'yyl', 'yym', 'yyn', 
        'yyp', 'yyq', 'yyr', 'yys', 'yyt', 'yyv', 'yyw', 'yyx', 'yyy', 'yyz', 'yzb', 'yzc', 
        'yzd', 'yzf', 'yzh', 'yzj', 'yzk', 'yzl', 'yzm', 'yzn', 'yzp', 'yzq', 'yzr', 'yzs', 
        'yzt', 'yzv', 'yzw', 'yzx', 'zaj', 'zao', 'zbb', 'zbc', 'zbd', 'zbf', 'zbg', 'zbh', 
        'zbj', 'zbk', 'zbl', 'zbm', 'zbn', 'zbp', 'zbq', 'zbs', 'zbt', 'zbv', 'zbw', 'zbx', 
        'zby', 'zbz', 'zcb', 'zcc', 'zcd', 'zcf', 'zcg', 'zci', 'zcj', 'zck', 'zcm', 'zcn', 
        'zco', 'zcp', 'zcq', 'zcr', 'zcs', 'zct', 'zcv', 'zcw', 'zcx', 'zcy', 'zcz', 'zdb', 
        'zdc', 'zdd', 'zdf', 'zdg', 'zdh', 'zdj', 'zdk', 'zdl', 'zdm', 'zdn', 'zdp', 'zdq', 
        'zds', 'zdt', 'zdv', 'zdw', 'zdx', 'zdy', 'zdz', 'zej', 'zex', 'zez', 'zfa', 'zfb', 
        'zfc', 'zfd', 'zff', 'zfg', 'zfh', 'zfi', 'zfj', 'zfk', 'zfm', 'zfn', 'zfo', 'zfp', 
        'zfq', 'zfr', 'zfs', 'zft', 'zfu', 'zfv', 'zfw', 'zfx', 'zfy', 'zfz', 'zgb', 'zgc', 
        'zgd', 'zge', 'zgf', 'zgg', 'zgj', 'zgk', 'zgm', 'zgn', 'zgp', 'zgq', 'zgr', 'zgs', 
        'zgt', 'zgu', 'zgv', 'zgw', 'zgx', 'zgy', 'zgz', 'zhb', 'zhc', 'zhd', 'zhf', 'zhg', 
        'zhh', 'zhj', 'zhl', 'zhp', 'zhq', 'zhr', 'zhs', 'zht', 'zhu', 'zhv', 'zhw', 'zhx', 
        'zhz', 'zij', 'ziy', 'zja', 'zjb', 'zjc', 'zjd', 'zje', 'zjf', 'zjg', 'zjh', 'zjj', 
        'zjk', 'zjl', 'zjm', 'zjn', 'zjo', 'zjp', 'zjq', 'zjr', 'zjs', 'zjt', 'zju', 'zjv', 
        'zjw', 'zjx', 'zjy', 'zjz', 'zkb', 'zkc', 'zkd', 'zkf', 'zkg', 'zkh', 'zkj', 'zkk', 
        'zkl', 'zkm', 'zkp', 'zkq', 'zks', 'zkt', 'zku', 'zkv', 'zkw', 'zkx', 'zkz', 'zlb', 
        'zlc', 'zld', 'zlf', 'zlg', 'zlh', 'zlj', 'zlk', 'zll', 'zlm', 'zln', 'zlp', 'zlq', 
        'zlr', 'zls', 'zlt', 'zlv', 'zlw', 'zlx', 'zlz', 'zmb', 'zmc', 'zmd', 'zmf', 'zmg', 
        'zmh', 'zmj', 'zmk', 'zml', 'zmm', 'zmn', 'zmp', 'zmq', 'zmr', 'zms', 'zmt', 'zmv', 
        'zmw', 'zmx', 'zmy', 'zmz', 'znb', 'znc', 'znd', 'znf', 'zng', 'znh', 'znj', 'znl', 
        'znm', 'znn', 'znp', 'znq', 'znr', 'zns', 'znt', 'znu', 'znv', 'znw', 'znx', 'zny', 
        'znz', 'zoj', 'zpb', 'zpc', 'zpd', 'zpe', 'zpf', 'zpg', 'zph', 'zpj', 'zpk', 'zpl', 
        'zpm', 'zpn', 'zpp', 'zpq', 'zpr', 'zps', 'zpt', 'zpu', 'zpv', 'zpw', 'zpx', 'zpz', 
        'zqa', 'zqb', 'zqc', 'zqd', 'zqe', 'zqf', 'zqg', 'zqh', 'zqi', 'zqj', 'zqk', 'zql', 
        'zqm', 'zqn', 'zqo', 'zqp', 'zqq', 'zqr', 'zqs', 'zqt', 'zqv', 'zqw', 'zqx', 'zqy', 
        'zqz', 'zrb', 'zrc', 'zrd', 'zrf', 'zrg', 'zrh', 'zri', 'zrj', 'zrk', 'zrl', 'zrm', 
        'zrn', 'zrp', 'zrq', 'zrr', 'zrs', 'zrt', 'zrv', 'zrw', 'zrx', 'zry', 'zrz', 'zsb', 
        'zsd', 'zse', 'zsf', 'zsg', 'zsh', 'zsi', 'zsj', 'zsm', 'zsn', 'zso', 'zsp', 'zsq', 
        'zsr', 'zss', 'zst', 'zsu', 'zsv', 'zsw', 'zsx', 'zsy', 'zsz', 'ztb', 'ztc', 'ztd', 
        'ztf', 'ztg', 'ztj', 'ztk', 'ztm', 'ztn', 'ztp', 'ztq', 'zts', 'ztt', 'ztu', 'ztv', 
        'ztw', 'ztx', 'zty', 'ztz', 'zua', 'zuj', 'zuq', 'zuv', 'zuw', 'zux', 'zuy', 'zvb', 
        'zvc', 'zvd', 'zve', 'zvf', 'zvg', 'zvh', 'zvi', 'zvj', 'zvk', 'zvl', 'zvm', 'zvn', 
        'zvp', 'zvq', 'zvr', 'zvs', 'zvt', 'zvu', 'zvv', 'zvw', 'zvx', 'zvy', 'zvz', 'zwb', 
        'zwc', 'zwd', 'zwe', 'zwf', 'zwg', 'zwh', 'zwj', 'zwk', 'zwl', 'zwm', 'zwn', 'zwp', 
        'zwq', 'zwr', 'zws', 'zwt', 'zwu', 'zwv', 'zww', 'zwx', 'zwy', 'zwz', 'zxa', 'zxb', 
        'zxc', 'zxd', 'zxe', 'zxf', 'zxg', 'zxh', 'zxi', 'zxj', 'zxk', 'zxl', 'zxm', 'zxn', 
        'zxo', 'zxp', 'zxq', 'zxr', 'zxs', 'zxt', 'zxu', 'zxv', 'zxw', 'zxx', 'zxy', 'zxz', 
        'zye', 'zyf', 'zyj', 'zyk', 'zyn', 'zyo', 'zyq', 'zyu', 'zyx', 'zyy', 'zzc', 'zzd', 
        'zzf', 'zzh', 'zzj', 'zzk', 'zzn', 'zzp', 'zzq', 'zzr', 'zzv', 'zzx', 'zzz'
        ]):
        continue
        
    if any(substring in combination_str for substring in [
        "jjjj", "jjjk", "jjjw", "jjjv", "jjjx", "jjjq",
        "jjkk", "jjkj", "jjkw", "jjkv", "jjkx", "jjkq",
        "jjww", "jjwj", "jjwk", "jjwv", "jjwx", "jjwq",
        "jjvz", "jjvj", "jjvk", "jjvw", "jjvx", "jjvq",
        "jjxf", "jjxj", "jjxk", "jjxw", "jjxv", "jjxq",
        "jjqq", "kkqq", "wwxj", "wwxk", "wwxv", "wwxq",
        "kkkk", "kkkj", "kkkw", "kkkv", "kkkx", "kkkq",
        "kkjj", "kkjk", "kkjw", "kkjv", "kkjx", "kkjq",
        "kkww", "kkwj", "kkwk", "kkwv", "kkwx", "kkwq",
        "kkvz", "kkvj", "kkvk", "kkvw", "kkvx", "kkvq",
        "kkxf", "kkxj", "kkxk", "kkxw", "kkxv", "kkxq",
        "wwwj", "wwwk", "wwwv", "wwwx", "wwwq", "wwqq",
        "wwvj", "wwvk", "wwvw", "wwvx", "wwvq", "wwqx",
        "xfjj", "xfjk", "xfjw", "xfjv", "xfjx", "xfjq",
        "xfkk", "xfkj", "xfkw", "xfkv", "xfkx", "xfkq",
        "xfww", "xfwj", "xfwk", "xfwv", "xfwx", "xfwq",
        "xfvz", "xfvj", "xfvk", "xfvw", "xfvx", "xfvq",
        "xfxf", "xfxj", "xfxk", "xfxw", "xfxv", "xfxq",
        "qjjj", "qjjk", "qjjw", "qjjv", "qjjx", "qjjq",
        "qjkk", "qjkj", "qjkw", "qjkv", "qjkx", "qjkq",
        "qjww", "qjwj", "qjwk", "qjwv", "qjwx", "qjwq",
        "qjvz", "qjvj", "qjvk", "qjvw", "qjvx", "qjvq",
        "qjxf", "qjxj", "qjxk", "qjxw", "qjxv", "qjxq",
        "wwqj", "wwqk", "wwqv", "vzzj", "vzzk", "vzzw",
        "vzzx", "vzzq", "vzvj", "vzvk", "vzvw", "vzvx",
        "vzvq", "vzxj", "vzxk", "vzxw", "vzxv", "vzxq",
        "vzqj", "vzqk", "vzqw", "vzqx", "vzqq", "xffj",
        "xffk", "xffw", "xffv", "xffq", "xfqq", "qjqq"
        ]):
        continue
    # Limits - end

    print("da")
    
    combination_with_space = combination_str + ' '
    combination_length = len(combination_with_space)

    if current_length + combination_length > aprox_chars_per_page:
        page_name = os.path.join(current_folder, f"Page_{page_index}.txt")
        with open(page_name, 'w') as page:
            for i in range(0, len(current_content), line_length):
                page.write(current_content[i:i+line_length] + '\n')

        current_content = ""
        current_length = 0

        page_index += 1

        if page_index > pages_per_book:
            folder_index += 1
            page_index = 1
            current_folder = os.path.join(main_folder, f"Book_{folder_index}")
            create_folder(current_folder)

    current_content += combination_with_space
    current_length += combination_length

# Write any remaining content to the last page
if current_content:
    page_name = os.path.join(current_folder, f"Page_{page_index}.txt")
    with open(page_name, 'w') as page:
        for i in range(0, len(current_content), line_length):
            page.write(current_content[i:i+line_length] + '\n')
